const legacyV3Action = action;
const legacyV3Bind = bind;

state.featureStep = Math.min(state.featureStep || 0, 1);
state.libraryTab ||= 'compare';
state.librarySort ||= project()?.task === 'regression' ? 'rmse' : 'auc';
state.showSavedVariants ||= false;
state.apiConfigs ||= [];

sidebar = function () {
  return `<aside class="sidebar"><div class="brand"><span>M</span><b>ML Studio</b></div><nav class="main-nav"><button data-page="home" class="${state.page === 'home' ? 'active' : ''}">⌂ 首页</button><button data-page="projects" class="${['projects', 'project', 'dataset', 'feature', 'experiments', 'model-select', 'experiment', 'tuning', 'report'].includes(state.page) ? 'active' : ''}">▣ 项目</button><button data-page="models" class="${['models', 'api'].includes(state.page) ? 'active' : ''}">◇ 模型库</button></nav><div class="sidebar-section"><div class="sidebar-title"><span>项目</span><button data-action="new-project">＋</button></div>${state.projects.map(item => `<button class="project-main sidebar-project ${item.id === state.projectId ? 'selected' : ''}" data-project="${item.id}"><span>${item.task === 'regression' ? 'R' : 'C'}</span><b>${esc(item.name)}</b></button>`).join('')}</div><div class="beginner-note"><b>初学者模式</b><span>按固定步骤完成训练，无需编写代码。</span></div></aside>`;
};

function datasetHover(set) {
  const numeric = set.columns.filter(column => column.type === 'number' && !column.target).slice(0, 2);
  return `<div class="dataset-hover"><div class="dataset-hover-head"><b>${esc(set.name)}</b><button data-pin-dataset="${set.id}" aria-label="固定弹窗">⌖ 固定</button></div><div class="dataset-hover-tabs"><button class="active" data-dataset-hover-tab="summary">数据概览</button><button data-dataset-hover-tab="preview">数据预览</button></div><div class="dataset-hover-panel active" data-dataset-hover-panel="summary"><div class="hover-stats"><span><b>${set.rows.toLocaleString()}</b>行</span><span><b>${set.columns.length}</b>列</span><span><b>${set.target}</b>目标列</span><span><b>${set.columns.reduce((sum, column) => sum + Math.round(column.missing * set.rows), 0)}</b>缺失值</span></div>${numeric.map((column, index) => `<div class="summary-row"><b>${esc(column.name)}</b><span>均值 ${(32.4 + index * 11.7).toFixed(1)}</span><span>中位数 ${(30.1 + index * 10.5).toFixed(1)}</span><span>最小 ${index}</span><span>最大 ${88 + index * 21}</span></div>`).join('')}<small>统计指标基于完整数据集，表格仅预览前 150 行。</small></div><div class="dataset-hover-panel" data-dataset-hover-panel="preview"><div class="mini-preview">${set.preview.slice(0, 5).map(row => `<div>${row.slice(0, 4).map(value => `<span>${esc(value)}</span>`).join('')}</div>`).join('')}</div><div class="hover-pagination"><button disabled>上一页</button><span>1 / 8</span><button>下一页</button></div><small>最多读取前 150 行，每页 20 行。</small></div></div>`;
}

projectPage = function () {
  const current = project(); const sets = current.datasets.map(id => state.datasets[id]).filter(Boolean);
  return shell(`${pageHead(esc(current.name), `${taskLabel(current.task)}项目 · 创建于 ${current.createdAt}`, `${button('查看本项目模型', 'project-models')}${button('＋ 添加数据集', 'upload-dataset', 'primary')}`)}<div class="stats-grid"><div class="stat"><span>数据集</span><b>${sets.length}</b></div><div class="stat"><span>模型实验</span><b>${sets.reduce((sum, set) => sum + set.experiments.length, 0)}</b></div><div class="stat"><span>已完成模型</span><b>${sets.flatMap(set => set.experiments).filter(id => state.experiments[id]?.status === 'completed').length}</b></div></div><div class="section-title"><h2>数据集</h2><span>悬浮查看完整统计摘要和前 150 行预览</span></div><div class="dataset-list">${sets.map(set => `<article class="dataset-card dataset-hover-host" tabindex="0" data-open-dataset="${set.id}"><div class="dataset-icon">▦</div><div><h3>${esc(set.name)}</h3><p>${set.rows.toLocaleString()} 行 · ${set.columns.length} 列 · 目标：${esc(set.target)}</p><span>上传于 ${set.uploadedAt}</span></div><div class="dataset-status"><b>${set.experiments.length}</b><span>模型实验</span></div><button class="btn">进入数据集</button>${datasetHover(set)}</article>`).join('')}</div>`);
};

steps = function (active) {
  const labels = [['dataset', '数据检查'], ['feature', '特征准备'], ['experiments', '模型训练'], ['tuning', '调参结果'], ['report', '模型报告']];
  const activeIndex = labels.findIndex(item => item[0] === active);
  return `<div class="stepper">${labels.map((item, index) => `<button data-page="${item[0]}" class="${index === activeIndex ? 'active' : index < activeIndex ? 'done' : ''}"><i>${index < activeIndex ? '✓' : index + 1}</i><span>${item[1]}</span></button>`).join('')}</div>`;
};

datasetPage = function () {
  const set = dataset(); const headers = set.columns.map(column => column.name); const classification = project().task === 'classification';
  const positives = classification ? [...new Set(set.preview.map(row => row[set.columns.findIndex(column => column.name === set.target)]))] : [];
  return shell(`${steps('dataset')}${pageHead('数据检查', `${esc(set.name)} · 创建数据集时确认目标列`, button('继续特征准备', 'go-feature', 'primary'))}<div class="stats-grid"><div class="stat"><span>数据量</span><b>${set.rows.toLocaleString()}</b><small>行</small></div><div class="stat"><span>字段数</span><b>${set.columns.length}</b><small>列</small></div><div class="stat"><span>目标列</span><select data-target-select>${set.columns.map(column => `<option ${column.name === set.target ? 'selected' : ''}>${esc(column.name)}</option>`).join('')}</select></div>${classification ? `<div class="stat"><span>正类</span><select data-positive-select>${positives.map(value => `<option ${value === set.positive ? 'selected' : ''}>${esc(value)}</option>`).join('')}</select><small>正类占比 26.5% · 使用分层划分</small></div>` : `<div class="stat"><span>任务类型</span><b class="small-value">回归</b></div>`}</div><div class="section-title"><h2>字段类型检查</h2><span>日期、自由文本和疑似 ID 标注为不可用于训练</span></div><div class="table-card"><table><thead><tr><th>字段</th><th>确认类型</th><th>缺失率</th><th>唯一值</th><th>一致性</th><th>训练可用性</th></tr></thead><tbody>${set.columns.map((column, index) => `<tr><td><b>${esc(column.name)}</b>${column.target ? '<small>目标列</small>' : ''}</td><td><select data-column-type="${index}">${['number', 'category', 'date', 'boolean', 'text'].map(type => `<option value="${type}" ${type === column.type ? 'selected' : ''}>${typeLabel(type)}</option>`).join('')}</select></td><td>${(column.missing * 100).toFixed(1)}%</td><td>${column.unique.toLocaleString()}</td><td><span class="status good">类型一致</span></td><td>${column.target ? '<span class="status target">目标列</span>' : column.trainable ? '<span class="status good">可用于训练</span>' : `<span class="status blocked">不可用于训练</span><small>${esc(column.reason)}</small>`}</td></tr>`).join('')}</tbody></table></div><div class="section-title"><h2>数据预览</h2><span>统计基于完整数据集；表格仅预览前 150 行</span></div><div class="table-card preview-table"><table><thead><tr>${headers.map(header => `<th>${esc(header)}</th>`).join('')}</tr></thead><tbody>${set.preview.map(row => `<tr>${row.map(value => `<td>${esc(value)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`);
};

featurePage = function () {
  const set = dataset(); const columns = set.columns.filter(column => !column.target); const classification = project().task === 'classification';
  return shell(`${steps('feature')}${pageHead('特征准备', '先划分数据，再仅使用训练集计算特征筛选指标。', button('保存并进入模型训练', 'go-experiments', 'primary'))}<div class="feature-layout"><aside class="feature-nav"><button data-feature-step="0" class="${state.featureStep === 0 ? 'active' : ''}"><i>1</i><span>训练集划分</span></button><button data-feature-step="1" class="${state.featureStep === 1 ? 'active' : ''}"><i>2</i><span>特征管理</span></button></aside><div class="feature-panel">${state.featureStep === 0 ? `<div class="panel-head"><div><h2>训练集 / 测试集划分</h2><p>${classification ? '二分类默认使用分层划分，保持正负类比例接近。' : '固定随机种子，保证不同模型使用相同测试样本。'}</p></div><span class="status good">随机种子 42</span></div><div class="ratio-grid">${['70-30', '75-25', '80-20', '90-10'].map(value => `<button data-split="${value}" class="${set.feature.split === value ? 'selected' : ''}"><b>${value.replace('-', '% / ')}%</b><span>${value === '80-20' ? '推荐' : '预设比例'}</span></button>`).join('')}</div>${button('下一步：特征管理', 'next-feature', 'primary')}` : `<div class="panel-head"><div><h2>特征管理</h2><p>以下指标仅根据训练集计算，测试集不参与特征筛选。</p></div>${button('采用自动推荐', 'apply-feature')}</div><div class="table-card"><table><thead><tr><th>纳入</th><th>特征</th><th>类型</th><th>缺失率</th>${classification ? '<th title="区分目标类别的能力，越大通常越有用">IV ⓘ</th>' : '<th title="方差过低表示特征变化很少">低方差 ⓘ</th><th title="特征与目标值的线性相关程度">目标相关性 ⓘ</th>'}<th title="分布稳定性指标">PSI ⓘ</th><th>状态</th></tr></thead><tbody>${columns.map((column, index) => `<tr><td><label class="switch"><input type="checkbox" data-feature-toggle="${index}" ${column.included ? 'checked' : ''} ${!column.trainable ? 'disabled' : ''}><span></span></label></td><td><b>${esc(column.name)}</b>${column.reason ? `<small>${esc(column.reason)}</small>` : ''}</td><td>${typeLabel(column.type)}</td><td>${(column.missing * 100).toFixed(1)}%</td>${classification ? `<td>${column.iv?.toFixed(3) ?? '—'}</td>` : `<td>${column.type === 'number' ? '正常' : '—'}</td><td>${column.type === 'number' ? (0.22 + index * .09).toFixed(2) : '—'}</td>`}<td>${column.psi?.toFixed(2) ?? '—'}</td><td>${!column.trainable ? '<span class="status blocked">不可用于训练</span>' : column.included ? '<span class="status good">已纳入</span>' : '<span class="status muted">已排除</span>'}</td></tr>`).join('')}</tbody></table></div>`}</div></div>`);
};

function missingDefault(type) {
  if (['lgbm', 'lgbmreg'].includes(type)) return ['不处理', '不处理'];
  if (['logistic', 'linear'].includes(type)) return ['均值填充', '保留为缺失类别'];
  return ['中位数填充', '保留为缺失类别'];
}

function compactParameters(item) {
  const definitions = {
    logistic: [['正则化强度 C', 1, '控制模型复杂度，推荐 1.0']], tree: [['最大深度', 6, '限制树的层数，推荐 6'], ['最小叶节点样本数', 10, '避免过度细分，推荐 10']], regtree: [['最大深度', 6, '限制树的层数，推荐 6'], ['最小叶节点样本数', 10, '避免过度细分，推荐 10']], forest: [['树数量', 200, '树越多通常越稳定，推荐 200'], ['最大深度', 8, '限制单棵树复杂度，推荐 8']], regforest: [['树数量', 200, '树越多通常越稳定，推荐 200'], ['最大深度', 8, '限制单棵树复杂度，推荐 8']], knn: [['邻居数量', 5, '参考最近的样本数量，推荐 5']], lgbm: [['树数量', 200, '提升轮数，推荐 200'], ['学习率', .05, '每次学习步长，推荐 0.05'], ['叶子数', 31, '控制树复杂度，推荐 31']], lgbmreg: [['树数量', 200, '提升轮数，推荐 200'], ['学习率', .05, '每次学习步长，推荐 0.05'], ['叶子数', 31, '控制树复杂度，推荐 31']]
  };
  const fields = definitions[item.type] || [];
  return fields.length ? `<div class="param-grid v4-params">${fields.map(([label, value, help]) => `<label><span>${label} <i title="${help}">ⓘ</i></span><input type="number" value="${value}"><small>${help}</small></label>`).join('')}</div><details class="advanced"><summary>高级参数设置</summary><label>随机种子<input value="42"></label><label>高级参数范围<input value="使用推荐范围"></label><button class="btn">恢复默认值</button></details>` : '<div class="notice">线性回归使用推荐默认配置，不展示常用可调参数。</div>';
}

experimentPage = function () {
  const item = experiment(); const defaults = missingDefault(item.type); const locked = item.status === 'completed';
  return shell(`${steps('experiments')}${pageHead(esc(item.name), `${modelName(item.type)} · ${esc(dataset().name)}${locked ? ' · 成功实验已锁定' : ''}`, `${button('返回实验列表', 'go-experiments')}${locked ? button('复制为新模型实验', 'clone-experiment', 'primary') : button('开始模拟训练', 'train', 'primary')}`)}<div class="config-grid"><section class="panel"><div class="panel-head"><div><h2>缺失值处理</h2><p>默认值根据模型选择，所有填充值只由训练集计算。</p></div></div><div class="missing-grid"><label>数值字段<select data-missing="numeric"><option>${defaults[0]}</option><option>不处理</option><option>均值填充</option><option>中位数填充</option><option>众数填充</option><option>固定值填充</option><option>删除所在行</option></select></label><label>类别字段<select data-missing="category"><option>${defaults[1]}</option><option>不处理</option><option>保留为缺失类别</option><option>众数填充</option><option>固定值填充</option><option>删除所在行</option></select></label></div><div class="field"><span>标准化</span><div class="toggle-line"><label class="switch"><input type="checkbox" data-standardize ${item.standardize ? 'checked' : ''} ${locked ? 'disabled' : ''}><span></span></label><b>${item.standardize ? '已开启' : '已关闭'}</b><small>${['logistic', 'knn', 'linear'].includes(item.type) ? '该模型推荐开启' : '该模型通常不需要'}</small></div></div></section><section class="panel"><div class="panel-head"><div><h2>模型参数</h2><p>默认只展示最重要参数，参数旁提供推荐值说明。</p></div></div>${compactParameters(item)}</section></div><section class="panel tuning-panel"><div class="panel-head"><div><h2>调参方式</h2><p>调参只在训练集内部交叉验证，测试集只用于最终报告。</p></div><span class="mock">模拟调参</span></div>${locked ? `<div class="notice">该实验已训练完成。如需调整配置，请复制为新模型实验。</div>` : tuningOptions(item)}</section>${state.training ? trainingPanel() : ''}`);
};

function sortedExperimentResults(item) {
  const key = state.tuningSort || (project().task === 'regression' ? 'rmse' : 'auc');
  const ascending = ['rmse', 'mae', 'gap'].includes(key);
  return [...item.results].sort((first, second) => ascending ? first[key] - second[key] : second[key] - first[key]);
}

tuningPage = function () {
  const item = experiment(); if (!item?.results?.length) return shell(`${steps('tuning')}${pageHead('调参结果', '完成模型训练后查看结果。')}<div class="empty-state"><h2>还没有结果</h2>${button('返回模型训练', 'go-experiment', 'primary')}</div>`);
  const regression = project().task === 'regression'; const options = regression ? [['rmse', '交叉验证 RMSE'], ['mae', '交叉验证 MAE'], ['r2', '交叉验证 R²'], ['gap', '训练/验证差值']] : [['auc', '交叉验证 AUC'], ['ks', 'KS'], ['f1', 'F1'], ['accuracy', '准确率'], ['recall', '召回率'], ['gap', '训练/验证差值']];
  const rows = (state.showAllResults ? sortedExperimentResults(item) : sortedExperimentResults(item).slice(0, 3));
  return shell(`${steps('tuning')}${pageHead('调参结果', `${esc(project().name)} / ${esc(dataset().name)} / ${esc(item.name)}`, `${button(state.showAllResults ? '仅看 Top 3' : '查看全部结果', 'toggle-results')}`)}<div class="tuning-toolbar"><label>排序指标<select data-tuning-sort>${options.map(option => `<option value="${option[0]}" ${(state.tuningSort || options[0][0]) === option[0] ? 'selected' : ''}>${option[1]}</option>`).join('')}</select></label><span>测试集不参与排序和 Top 3 选择</span></div><div class="table-card"><table class="result-table"><thead><tr><th>保存</th><th>排名</th><th>参数方案</th>${regression ? '<th title="交叉验证均方根误差，越小越好">CV RMSE ⓘ ↓</th><th title="交叉验证平均绝对误差，越小越好">CV MAE ⓘ ↓</th><th title="解释目标变化的比例，越大越好">CV R² ⓘ ↑</th>' : '<th title="交叉验证区分能力，越大越好">CV AUC ⓘ ↑</th><th title="正负类最大区分度，越大越好">KS ⓘ ↑</th><th title="精确率和召回率的平衡，越大越好">F1 ⓘ ↑</th>'}<th title="训练与验证表现差距，越小越好">差值 ⓘ ↓</th><th>操作</th></tr></thead><tbody>${rows.map((result, index) => `<tr><td><input type="checkbox" data-save-result="${result.id}" ${index < 3 ? 'checked' : ''}></td><td><b>#${index + 1}</b>${index === 0 ? '<small>主方案</small>' : ''}</td><td>${result.params}</td>${regression ? `<td>${result.rmse}</td><td>${result.mae}</td><td>${result.r2}</td>` : `<td>${result.auc}</td><td>${result.ks}</td><td>${result.f1}</td>`}<td>${result.gap}</td><td><div class="row-actions">${button('设为主方案', `select-result:${result.id}`)}${button('查看模型报告', `report-result:${result.id}`, 'primary')}</div></td></tr>`).join('')}</tbody></table></div><div class="save-note"><b>默认勾选 Top 3 参数方案保存到模型库</b><span>这些方案属于同一个模型实验，不是三个独立模型。</span></div>`);
};

classificationCharts = function () { return `<div class="chart-grid"><div class="chart-card"><h3>ROC 曲线</h3><div class="fake-chart roc"><i></i></div><p>曲线越靠近左上角，区分能力越好。</p></div><div class="chart-card"><h3>Gain Table</h3><p class="lift-help"><b>Lift：</b>模型筛选效果相对随机筛选提升了多少倍，越大越好。</p><table><thead><tr><th>累计人群</th><th>累计正类捕获</th><th title="Lift = 3，表示命中率约为随机筛选的 3 倍。">Lift ⓘ</th></tr></thead><tbody><tr><td>10%</td><td>31%</td><td>3.10</td></tr><tr><td>20%</td><td>58%</td><td>2.90</td></tr><tr><td>30%</td><td>76%</td><td>2.53</td></tr></tbody></table></div></div>`; };

const legacyReportPageV4 = reportPage;
reportPage = function () { return legacyReportPageV4().replace(button('API 接入说明', 'go-api', 'primary'), ''); };

function libraryRows() {
  const currentProject = project(); const currentDataset = dataset(); const regression = currentProject.task === 'regression';
  const experiments = Object.values(state.experiments).filter(item => item.projectId === currentProject.id && item.datasetId === currentDataset?.id && item.results?.length);
  const rows = experiments.flatMap(item => { const primary = item.results.find(result => result.id === item.selected) || item.results[0]; const results = state.showSavedVariants ? item.results.slice(0, 3) : [primary]; return results.map(result => ({ item, result, primary: result.id === primary.id })); });
  const key = state.librarySort || (regression ? 'rmse' : 'auc'); const ascending = ['rmse', 'mae', 'gap'].includes(key);
  return rows.sort((first, second) => ascending ? first.result[key] - second.result[key] : second.result[key] - first.result[key]);
}

modelsPage = function () {
  const currentProject = project(); const sets = currentProject.datasets.map(id => state.datasets[id]).filter(Boolean); const currentDataset = dataset(); const regression = currentProject.task === 'regression';
  const options = regression ? [['rmse', 'RMSE'], ['mae', 'MAE'], ['r2', 'R²'], ['gap', '训练/验证差值']] : [['auc', 'AUC'], ['ks', 'KS'], ['f1', 'F1'], ['accuracy', '准确率'], ['recall', '召回率'], ['gap', '训练/验证差值']]; const rows = currentDataset ? libraryRows() : [];
  const compare = `<div class="library-toolbar"><label>项目<select data-library-project>${state.projects.map(item => `<option value="${item.id}" ${item.id === currentProject.id ? 'selected' : ''}>${esc(item.name)}</option>`).join('')}</select></label><label>数据集<select data-library-dataset>${sets.map(item => `<option value="${item.id}" ${item.id === currentDataset?.id ? 'selected' : ''}>${esc(item.name)}</option>`).join('')}</select></label><label>排序<select data-library-sort>${options.map(option => `<option value="${option[0]}" ${state.librarySort === option[0] ? 'selected' : ''}>${option[1]}</option>`).join('')}</select></label><label class="library-check"><input type="checkbox" data-show-variants ${state.showSavedVariants ? 'checked' : ''}> 展开已保存 Top 3</label></div>${rows.length ? `<div class="table-card"><table class="result-table"><thead><tr><th>模型实验</th><th>模型类型</th><th>参数方案</th>${regression ? '<th>RMSE ↓</th><th>MAE ↓</th><th>R² ↑</th>' : '<th>AUC ↑</th><th>KS ↑</th><th>F1 ↑</th>'}<th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(({ item, result, primary }) => `<tr><td><b>${esc(item.name)}</b><small>${esc(currentDataset.name)}</small></td><td>${modelName(item.type)}</td><td>${result.params}${primary ? '<small>主方案</small>' : '<small>已保存方案</small>'}</td>${regression ? `<td>${result.rmse}</td><td>${result.mae}</td><td>${result.r2}</td>` : `<td>${result.auc}</td><td>${result.ks}</td><td>${result.f1}</td>`}<td><span class="status good">已完成</span></td><td><div class="row-actions">${button('查看结果', `library-result:${item.id}:${result.id}`)}${button('生成 API 配置', `open-api-config:${item.id}:${result.id}`)}</div></td></tr>`).join('')}</tbody></table></div>` : '<div class="empty-state"><h2>该数据集暂无已完成结果</h2><p>创建新模型并完成模拟训练后，结果会显示在这里。</p></div>'}`;
  const services = `<div class="table-card"><table><thead><tr><th>服务名称</th><th>绑定模型</th><th>参数方案</th><th>创建时间</th><th>状态</th><th>操作</th></tr></thead><tbody>${state.apiConfigs.length ? state.apiConfigs.map(config => { const item = state.experiments[config.experimentId]; return `<tr><td><b>${esc(config.name)}</b></td><td>${esc(item?.name || '模型已删除')}</td><td>#${config.resultId}</td><td>${config.createdAt}</td><td><span class="status good">演示配置</span></td><td><div class="row-actions">${item ? button('查看接入说明', `view-api-config:${config.id}`) : ''}${button('删除', `delete-api-config:${config.id}`)}</div></td></tr>`; }).join('') : '<tr><td colspan="6"><div class="empty-state"><p>尚未生成 API 接入配置。</p></div></td></tr>'}</tbody></table></div>`;
  return shell(`${pageHead('模型库', '比较同一数据集下的模型结果，并管理演示 API 接入配置。')}<div class="library-tabs"><button data-action="library-tab:compare" class="${state.libraryTab === 'compare' ? 'active' : ''}">模型比较</button><button data-action="library-tab:api" class="${state.libraryTab === 'api' ? 'active' : ''}">API 服务</button></div>${state.libraryTab === 'api' ? services : compare}`);
};

function apiConfigModal(experimentId, resultId) {
  const item = state.experiments[experimentId];
  modal(`<h2>生成 API 接入配置</h2><p>配置绑定到当前模型实验的指定参数方案，当前仅提供前端演示。</p><label class="field"><span>服务名称</span><input id="api-service-name" value="${esc(item.name)} API"></label><label class="field"><span>参数方案</span><select id="api-result-id">${item.results.slice(0, 3).map(result => `<option value="${result.id}" ${result.id === +resultId ? 'selected' : ''}>#${result.id} · ${esc(result.params)}</option>`).join('')}</select></label><div class="modal-actions">${button('取消', 'close-modal')}${button('确认生成', `confirm-api-config:${experimentId}`, 'primary')}</div>`);
  const modalElement = document.querySelector('.modal-backdrop'); modalElement.querySelector('[data-action^="confirm-api-config"]').onclick = event => { event.stopPropagation(); action(event.currentTarget.dataset.action); };
}

function datasetSourceModal() {
  modal(`<h2>添加数据集</h2><p>上传自己的 CSV，或选择符合当前${taskLabel(project().task)}项目的示例。</p><div class="source-tabs"><button class="active" data-source-tab="upload">上传 CSV</button><button data-source-tab="example">示例数据集</button></div><div class="source-panel active" data-source-panel="upload"><div class="upload-box">${button('选择 CSV 文件', 'choose-csv', 'primary')}<span>支持 UTF-8、带表头的 CSV</span></div></div><div class="source-panel" data-source-panel="example">${project().task === 'regression' ? button('使用住宅价格示例', 'use-example:housing', 'primary') : button('使用客户流失示例', 'use-example:churn', 'primary')}</div><div class="modal-actions">${button('取消', 'close-modal')}</div>`);
  const modalElement = document.querySelector('.modal-backdrop');
  modalElement.querySelectorAll('[data-action]').forEach(element => { if (element.dataset.action !== 'close-modal') element.onclick = () => action(element.dataset.action); });
  modalElement.querySelectorAll('[data-source-tab]').forEach(element => element.onclick = () => { modalElement.querySelectorAll('[data-source-tab]').forEach(tab => tab.classList.toggle('active', tab === element)); modalElement.querySelectorAll('[data-source-panel]').forEach(panel => panel.classList.toggle('active', panel.dataset.sourcePanel === element.dataset.sourceTab)); });
}

const previousActionV4 = action;
action = function (name) {
  if (name === 'upload-dataset') return datasetSourceModal();
  if (name === 'choose-csv') { document.querySelector('.modal-backdrop')?.remove(); return fileInput.click(); }
  if (name.startsWith('use-example:')) { document.querySelector('.modal-backdrop')?.remove(); const kind = name.split(':')[1] === 'housing' ? 'housing' : 'churn'; const id = uid('d'); const columns = structuredClone(exampleColumns[kind]); const preview = structuredClone(previews[kind]); const target = kind === 'housing' ? '房价' : '是否流失'; state.datasets[id] = { id, projectId: project().id, name: kind === 'housing' ? '住宅价格示例' : '客户流失示例', uploadedAt: now(), rows: kind === 'housing' ? 1460 : 7043, target, positive: kind === 'housing' ? '' : '是', columns, preview, feature: { split: '80-20', revision: 1 }, experiments: [] }; project().datasets.push(id); state.datasetId = id; save(); return go('dataset'); }
  if (name === 'clone-experiment') { const source = experiment(); const id = uid('e'); const sameType = dataset().experiments.map(expId => state.experiments[expId]).filter(item => item.type === source.type).length + 1; state.experiments[id] = { ...structuredClone(source), id, name: `${modelName(source.type)} ${String(sameType).padStart(2, '0')}`, status: 'draft', results: [], selected: null, updatedAt: now() }; dataset().experiments.push(id); state.experimentId = id; save(); return go('experiment'); }
  if (name.startsWith('report-result:')) { experiment().selected = +name.split(':')[1]; save(); return go('report'); }
  if (name.startsWith('library-tab:')) { state.libraryTab = name.split(':')[1]; save(); return render(); }
  if (name.startsWith('library-result:')) { const [, experimentId, resultId] = name.split(':'); const item = state.experiments[experimentId]; state.projectId = item.projectId; state.datasetId = item.datasetId; state.experimentId = item.id; item.selected = +resultId; save(); return go('tuning'); }
  if (name.startsWith('open-api-config:')) { const [, experimentId, resultId] = name.split(':'); return apiConfigModal(experimentId, resultId); }
  if (name.startsWith('confirm-api-config:')) { const experimentId = name.split(':')[1]; const serviceName = document.querySelector('#api-service-name').value.trim(); if (!serviceName) return toast('请输入服务名称。'); const resultId = +document.querySelector('#api-result-id').value; state.apiConfigs.push({ id: uid('api'), name: serviceName, experimentId, resultId, createdAt: now() }); document.querySelector('.modal-backdrop')?.remove(); state.libraryTab = 'api'; save(); return render(); }
  if (name.startsWith('view-api-config:')) { const config = state.apiConfigs.find(item => item.id === name.split(':')[1]); const item = state.experiments[config.experimentId]; state.projectId = item.projectId; state.datasetId = item.datasetId; state.experimentId = item.id; item.selected = config.resultId; save(); return go('api'); }
  if (name.startsWith('delete-api-config:')) { state.apiConfigs = state.apiConfigs.filter(item => item.id !== name.split(':')[1]); save(); return render(); }
  return previousActionV4(name);
};

const previousBindV4 = bind;
bind = function () {
  previousBindV4();
  app.querySelectorAll('[data-dataset-hover-tab]').forEach(buttonElement => buttonElement.onclick = event => { event.stopPropagation(); const popup = buttonElement.closest('.dataset-hover'); popup.querySelectorAll('[data-dataset-hover-tab]').forEach(tab => tab.classList.toggle('active', tab === buttonElement)); popup.querySelectorAll('[data-dataset-hover-panel]').forEach(panel => panel.classList.toggle('active', panel.dataset.datasetHoverPanel === buttonElement.dataset.datasetHoverTab)); });
  app.querySelectorAll('[data-pin-dataset]').forEach(buttonElement => buttonElement.onclick = event => { event.stopPropagation(); buttonElement.closest('.dataset-hover').classList.toggle('pinned'); });
  document.querySelector('[data-target-select]')?.addEventListener('change', event => { const set = dataset(); set.columns.forEach(column => { column.target = column.name === event.target.value; if (column.target) column.included = false; }); set.target = event.target.value; set.feature.revision += 1; markDatasetStale(set); save(); render(); });
  document.querySelector('[data-positive-select]')?.addEventListener('change', event => { dataset().positive = event.target.value; save(); });
  document.querySelector('[data-tuning-sort]')?.addEventListener('change', event => { state.tuningSort = event.target.value; save(); render(); });
  document.querySelector('[data-library-project]')?.addEventListener('change', event => { state.projectId = event.target.value; state.datasetId = project().datasets[0]; state.librarySort = project().task === 'regression' ? 'rmse' : 'auc'; save(); render(); });
  document.querySelector('[data-library-dataset]')?.addEventListener('change', event => { state.datasetId = event.target.value; save(); render(); });
  document.querySelector('[data-library-sort]')?.addEventListener('change', event => { state.librarySort = event.target.value; save(); render(); });
  document.querySelector('[data-show-variants]')?.addEventListener('change', event => { state.showSavedVariants = event.target.checked; save(); render(); });
  document.querySelectorAll('[data-source-tab]').forEach(buttonElement => buttonElement.onclick = () => { const modalElement = buttonElement.closest('.modal'); modalElement.querySelectorAll('[data-source-tab]').forEach(tab => tab.classList.toggle('active', tab === buttonElement)); modalElement.querySelectorAll('[data-source-panel]').forEach(panel => panel.classList.toggle('active', panel.dataset.sourcePanel === buttonElement.dataset.sourceTab)); });
};

render();
