state.resultScope ||= 'validation';
state.libraryProjectId ||= 'all';
state.libraryDatasetId ||= 'all';
Object.values(state.experiments).forEach(item => { if (item.tuning === 'auto' && item.results?.length > 3) item.results = item.results.slice(0, 3); });

function addExampleFeaturesV6(columns, preview, extras, valuesByRow) {
  const missing = extras.filter(extra => !columns.some(column => column.name === extra.name)); if (!missing.length) return; const targetIndex = columns.findIndex(column => column.target); columns.splice(targetIndex < 0 ? columns.length : targetIndex, 0, ...missing); preview.forEach((row, rowIndex) => row.splice(Math.max(0, row.length - 1), 0, ...(valuesByRow[rowIndex % valuesByRow.length] || valuesByRow[0])));
}

const classificationExampleFeaturesV6 = [
  { name: '年龄', type: 'number', missing: .01, unique: 63, trainable: true, iv: .16, psi: .07, included: true }, { name: '性别', type: 'category', missing: 0, unique: 2, trainable: true, iv: .03, psi: .04, included: true }, { name: '是否老年', type: 'boolean', missing: 0, unique: 2, trainable: true, iv: .09, psi: .06, included: true }, { name: '是否有配偶', type: 'category', missing: .01, unique: 2, trainable: true, iv: .11, psi: .08, included: true }, { name: '互联网服务', type: 'category', missing: .02, unique: 3, trainable: true, iv: .21, psi: .09, included: true }, { name: '在线安全服务', type: 'category', missing: .03, unique: 3, trainable: true, iv: .14, psi: .12, included: true }, { name: '技术支持', type: 'category', missing: .02, unique: 3, trainable: true, iv: .17, psi: .1, included: true }, { name: '无纸化账单', type: 'boolean', missing: 0, unique: 2, trainable: true, iv: .08, psi: .05, included: true }
];
const regressionExampleFeaturesV6 = [
  { name: '地块面积', type: 'number', missing: 0, unique: 1073, trainable: true, psi: .06, included: true }, { name: '总房间数', type: 'number', missing: 0, unique: 12, trainable: true, psi: .08, included: true }, { name: '浴室数', type: 'number', missing: .01, unique: 6, trainable: true, psi: .05, included: true }, { name: '车库面积', type: 'number', missing: .04, unique: 441, trainable: true, psi: .13, included: true }, { name: '房屋质量', type: 'number', missing: 0, unique: 10, trainable: true, psi: .07, included: true }, { name: '翻修年份', type: 'number', missing: .02, unique: 61, trainable: true, psi: .09, included: true }, { name: '社区', type: 'category', missing: 0, unique: 25, trainable: true, psi: .11, included: true }, { name: '房屋类型', type: 'category', missing: 0, unique: 5, trainable: true, psi: .04, included: true }
];
addExampleFeaturesV6(exampleColumns.churn, previews.churn, classificationExampleFeaturesV6, [[35, '女', false, '是', '光纤', '是', '否', true], [62, '男', true, '否', 'DSL', '否', '否', true], [28, '女', false, '否', '光纤', '否', '是', false], [47, '男', false, '是', '无', '不适用', '不适用', true]]);
addExampleFeaturesV6(exampleColumns.housing, previews.housing, regressionExampleFeaturesV6, [[8450, 8, 2, 548, 7, 2003, 'CollgCr', '独栋'], [9600, 6, 2, 460, 6, 1976, 'Veenker', '独栋'], [11250, 7, 2, 608, 7, 2002, 'CollgCr', '独栋'], [9550, 9, 1, 642, 7, 1970, 'Crawfor', '联排']]);
if (state.datasets['d-churn']?.columns !== exampleColumns.churn) addExampleFeaturesV6(state.datasets['d-churn'].columns, state.datasets['d-churn'].preview, classificationExampleFeaturesV6, [[35, '女', false, '是', '光纤', '是', '否', true], [62, '男', true, '否', 'DSL', '否', '否', true], [28, '女', false, '否', '光纤', '否', '是', false], [47, '男', false, '是', '无', '不适用', '不适用', true]]);
if (state.datasets['d-house']?.columns !== exampleColumns.housing) addExampleFeaturesV6(state.datasets['d-house'].columns, state.datasets['d-house'].preview, regressionExampleFeaturesV6, [[8450, 8, 2, 548, 7, 2003, 'CollgCr', '独栋'], [9600, 6, 2, 460, 6, 1976, 'Veenker', '独栋'], [11250, 7, 2, 608, 7, 2002, 'CollgCr', '独栋'], [9550, 9, 1, 642, 7, 1970, 'Crawfor', '联排']]);

const previousActionV6 = action;
const previousBindV6 = bind;
const recommendedThresholdsV6 = { missing: 90, iv: .01, variance: .01, targetCorrelation: .05, psi: .25 };

const previousHomePageV6 = homePage;
homePage = function () { return previousHomePageV6().replaceAll('特征工程', '特征准备').replaceAll('模型实验</span><i>→</i><span>4 查看结果', '模型训练</span><i>→</i><span>4 训练结果'); };

sidebar = function () {
  return `<aside class="sidebar"><div class="brand"><span>M</span><b>ML Studio</b></div><nav class="main-nav"><button data-page="home" class="${state.page === 'home' ? 'active' : ''}">⌂ 首页</button><button data-page="projects" class="${['projects', 'project', 'dataset', 'feature', 'experiments', 'model-select', 'experiment', 'tuning', 'report'].includes(state.page) ? 'active' : ''}">▣ 项目</button><button data-page="models" class="${['models', 'api'].includes(state.page) ? 'active' : ''}">◇ 模型库</button></nav><div class="beginner-note"><b>初学者模式</b><span>按固定步骤完成训练，无需编写代码。</span></div></aside>`;
};

steps = function (active) {
  if (active === 'report') return '';
  const labels = [['dataset', '数据检查'], ['feature', '特征准备'], ['experiments', '模型训练'], ['tuning', '训练结果']]; const activeIndex = labels.findIndex(item => item[0] === active);
  return `<div class="stepper">${labels.map((item, index) => `<button data-page="${item[0]}" class="${index === activeIndex ? 'active' : index < activeIndex ? 'done' : ''}"><i>${index < activeIndex ? '✓' : index + 1}</i><span>${item[1]}</span></button>`).join('')}</div>`;
};

projectPage = function () {
  const current = project(); const sets = current.datasets.map(id => state.datasets[id]).filter(Boolean);
  return shell(`${pageHead(esc(current.name), `${taskLabel(current.task)}项目 · 创建于 ${current.createdAt}`, `${button('查看本项目模型', 'project-models')}${button('＋ 添加数据集', 'upload-dataset', 'primary')}`)}<div class="stats-grid"><div class="stat"><span>数据集</span><b>${sets.length}</b></div><div class="stat"><span>模型实验</span><b>${sets.reduce((sum, set) => sum + set.experiments.length, 0)}</b></div><div class="stat"><span>已完成模型</span><b>${sets.flatMap(set => set.experiments).filter(id => state.experiments[id]?.status === 'completed').length}</b></div></div><div class="section-title"><h2>数据集</h2><span>悬浮查看统计表和原始数据预览</span></div><div class="dataset-list">${sets.map(set => `<article class="dataset-card dataset-hover-host" tabindex="0"><div class="dataset-icon">▦</div><div><h3>${esc(set.name)}</h3><p>${set.rows.toLocaleString()} 行 · ${set.columns.length} 列 · 目标：${esc(set.target)}</p><span>上传于 ${set.uploadedAt}</span></div><div class="dataset-status"><b>${set.experiments.length}</b><span>模型实验</span></div><div class="dataset-entry-actions">${button('进入数据集', `enter-dataset:${set.id}`, 'primary')}${button(`模型实验（${set.experiments.length}）`, `enter-experiments:${set.id}`)}</div>${datasetHover(set)}</article>`).join('')}</div>`);
};

datasetHover = function (set) {
  const summaryPage = state.hoverSummaryPage?.[set.id] || 0; const previewPage = state.hoverPreviewPage?.[set.id] || 0; const activeTab = state.hoverTab?.[set.id] || 'summary'; const summaryColumns = set.columns.slice(0, 50); const summaryPages = Math.max(1, Math.ceil(summaryColumns.length / 10)); const shownColumns = summaryColumns.slice(summaryPage * 10, summaryPage * 10 + 10); const previewPages = Math.max(1, Math.ceil(Math.min(150, set.rows) / 20)); const headers = set.columns.slice(0, 7); const sourceRows = set.preview.length ? set.preview : [[]]; const rows = Array.from({ length: Math.min(20, sourceRows.length) }, (_, index) => sourceRows[(previewPage * 20 + index) % sourceRows.length]);
  return `<div class="dataset-hover"><div class="dataset-hover-head"><b>${esc(set.name)}</b><button data-pin-dataset="${set.id}">⌖ 固定</button></div><div class="dataset-hover-tabs"><button class="${activeTab === 'summary' ? 'active' : ''}" data-dataset-hover-tab="summary">数据概览</button><button class="${activeTab === 'preview' ? 'active' : ''}" data-dataset-hover-tab="preview">数据预览</button></div><div class="dataset-hover-panel ${activeTab === 'summary' ? 'active' : ''}" data-dataset-hover-panel="summary"><div class="hover-stats"><span><b>${set.rows.toLocaleString()}</b>行</span><span><b>${set.columns.length}</b>列</span><span><b>${esc(set.target)}</b>目标列</span><span><b>${set.columns.reduce((sum, column) => sum + Math.round(column.missing * set.rows), 0)}</b>缺失值</span></div><div class="hover-table-wrap"><table class="hover-table"><thead><tr><th>特征</th><th>类型</th><th>缺失率</th><th>均值</th><th>中位数</th><th>最小值</th><th>最大值</th><th>类别数 / Top 类别</th></tr></thead><tbody>${shownColumns.map((column, index) => `<tr><td>${esc(column.name)}</td><td>${typeLabel(column.type)}</td><td>${(column.missing * 100).toFixed(1)}%</td>${column.type === 'number' ? `<td>${(32.4 + index * 4.3).toFixed(1)}</td><td>${(30.1 + index * 3.8).toFixed(1)}</td><td>${index}</td><td>${88 + index * 9}</td><td>—</td>` : `<td>—</td><td>—</td><td>—</td><td>—</td><td>${column.unique} / 示例类别</td>`}</tr>`).join('')}</tbody></table></div><div class="hover-pagination"><button data-hover-summary="${set.id}:-1" ${summaryPage === 0 ? 'disabled' : ''}>上一页</button><span>${summaryPage + 1} / ${summaryPages}</span><button data-hover-summary="${set.id}:1" ${summaryPage >= summaryPages - 1 ? 'disabled' : ''}>下一页</button></div><small>展示前 50 个特征的统计指标，每页 10 个。</small></div><div class="dataset-hover-panel ${activeTab === 'preview' ? 'active' : ''}" data-dataset-hover-panel="preview"><div class="hover-table-wrap"><table class="hover-table"><thead><tr>${headers.map(column => `<th>${esc(column.name)}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${headers.map((column, index) => `<td>${esc(row[index] ?? '—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="hover-pagination"><button data-hover-preview="${set.id}:-1" ${previewPage === 0 ? 'disabled' : ''}>上一页</button><span>${previewPage + 1} / ${previewPages}</span><button data-hover-preview="${set.id}:1" ${previewPage >= previewPages - 1 ? 'disabled' : ''}>下一页</button></div><small>最多读取前 150 行，每页 20 行。</small></div></div>`;
};

thresholdControls = function () {
  const values = state.featureThresholds; const classification = project().task === 'classification';
  return `<div class="threshold-panel v6-thresholds"><div><b>筛选阈值</b><span>推荐阈值只恢复数字；确定修改后按当前数字筛选。</span></div><label>缺失率上限<input data-threshold="missing" type="number" value="${values.missing}"><em>%</em></label>${classification ? `<label>IV 下限 <i title="区分正负类别的能力，通常越大越强；超过 0.5 时需警惕泄漏。">ⓘ</i><input data-threshold="iv" type="number" step="0.01" value="${values.iv}"></label>` : `<label>低方差阈值 <i title="数值越小通常表示特征变化越少。">ⓘ</i><input data-threshold="variance" type="number" step="0.01" value="${values.variance}"></label><label>目标相关性下限 <i title="绝对值越大通常线性关系越明显；接近零不代表一定无用。">ⓘ</i><input data-threshold="targetCorrelation" type="number" step="0.01" value="${values.targetCorrelation}"></label>`}<label>PSI 上限 <i title="越小越稳定：低于 0.1 稳定，0.1–0.25 需关注，达到 0.25 表示变化明显。">ⓘ</i><input data-threshold="psi" type="number" step="0.01" value="${values.psi ?? .25}"></label><div class="threshold-actions">${button('推荐阈值', 'recommend-thresholds')}${button('确定修改', 'confirm-thresholds', 'primary')}</div></div><details class="metric-guide compact-guide"><summary>查看指标说明</summary>${classification ? '<div><b>IV</b><span>&lt;0.02 作用较弱；0.02–0.1 较弱；0.1–0.3 中等；0.3–0.5 较强；超过 0.5 需警惕泄漏。</span></div>' : '<div><b>低方差</b><span>数值较小通常表示特征变化不足。</span></div><div><b>目标相关性</b><span>绝对值越大通常线性关系越明显，接近零不代表一定无用。</span></div>'}<div><b>PSI</b><span>&lt;0.1 稳定；0.1–0.25 需关注；≥0.25 分布变化明显。</span></div></details>`;
};

function correlationValuesV6() {
  const columns = dataset().columns.filter(column => column.type === 'number' && !column.target).slice(0, 8); const pairs = [];
  columns.forEach((first, firstIndex) => columns.forEach((second, secondIndex) => { if (secondIndex <= firstIndex) return; const score = Math.max(.12, .92 - Math.abs(firstIndex - secondIndex) * .09); pairs.push({ first, second, score: +score.toFixed(2) }); }));
  return { columns, pairs };
}

correlationPanel = function () {
  const { columns, pairs } = correlationValuesV6(); if (columns.length < 2) return ''; const scoreFor = (first, second) => first === second ? 1 : pairs.find(pair => pair.first === first && pair.second === second || pair.first === second && pair.second === first)?.score || 0;
  return `<section class="correlation-panel"><div class="panel-head"><div><h2>特征相关性热力图</h2><p>仅使用训练集数值特征计算。</p></div><div class="correlation-actions"><label>预警阈值<input data-correlation-draft type="number" step="0.05" value="${state.featureThresholds.correlation}"></label><span data-correlation-unsaved hidden>尚未应用</span>${button('确定修改', 'confirm-correlation-threshold')}${button('自动处理高相关特征', 'preview-correlation')}</div></div><div class="heat-legend"><span>低相关</span><i></i><span>高相关</span></div><div class="correlation-grid" style="--count:${columns.length + 1}"><i></i>${columns.map(column => `<b>${esc(column.name)}</b>`).join('')}${columns.map(row => `<b>${esc(row.name)}</b>${columns.map(column => { const score = scoreFor(row, column); const lightness = 97 - Math.round(score * 48); return `<span style="background:hsl(213 88% ${lightness}%);color:${score > .62 ? '#fff' : '#17345f'}" class="${row !== column && score >= state.featureThresholds.correlation ? 'warning' : ''}">${score.toFixed(2)}</span>`; }).join('')}`).join('')}</div><small>达到已确认阈值时预警；修改输入框后需点击“确定修改”。</small></section>`;
};

enhanceFeaturePage = function () {
  if (state.page !== 'feature') return; app.querySelectorAll('.feature-panel h2,.feature-panel p,.page-head p').forEach(element => { element.textContent = element.textContent.replaceAll('测试集', '验证集'); }); app.querySelectorAll('.feature-panel .status').forEach(element => { if (element.textContent.includes('随机种子')) element.remove(); }); if (state.featureStep !== 1) return; const table = app.querySelector('.feature-panel .table-card'); if (!table) return;
  const autoButton = app.querySelector('.feature-panel [data-action="apply-feature"]'); if (autoButton) { autoButton.textContent = '自动筛选'; autoButton.dataset.action = 'auto-filter-v6'; autoButton.classList.add('primary'); }
  table.insertAdjacentHTML('beforebegin', thresholdControls()); app.querySelector('.feature-panel').insertAdjacentHTML('beforeend', correlationPanel());
};

function gridCountV6(container) {
  const fields = [...container.querySelectorAll('[data-grid-values]')].filter(input => !input.disabled); let valid = true; const counts = fields.map(input => { const count = input.value.split(',').map(value => value.trim()).filter(Boolean).length; if (!count) valid = false; return count; }); const total = valid ? counts.reduce((product, count) => product * count, 1) : 0; const output = container.querySelector('[data-grid-count]'); output.textContent = valid ? `共需训练 ${total} 组参数组合${total > 200 ? ' · 组合较多，预计耗时较长' : ''}` : '请为每个参数填写至少一个候选值'; output.classList.toggle('warning-text', total > 200 || !valid);
}

enhanceExperimentPage = function () {
  if (state.page !== 'experiment') return; const item = experiment(); const details = app.querySelector('.config-grid details.advanced'); const advanced = advancedParameters(item.type);
  app.querySelectorAll('.tuning-panel p').forEach(element => { element.textContent = element.textContent.replace('调参只在训练集内部交叉验证，测试集只用于最终报告。', '每组参数在训练集训练，并计算训练集与验证集指标。'); });
  const choices = { 求解器: ['lbfgs', 'liblinear', 'saga'], 划分标准: item.type.includes('reg') ? ['squared_error', 'friedman_mse', 'absolute_error'] : ['gini', 'entropy', 'log_loss'], 最大特征数: ['全部', 'sqrt', 'log2'], 距离权重: ['uniform', 'distance'], 距离度量: ['minkowski', 'euclidean', 'manhattan'] };
  if (details) details.innerHTML = `<summary>高级参数设置</summary><div class="advanced-grid">${advanced.map(([name, value, help]) => `<label><span>${name}</span>${choices[name] ? `<select>${choices[name].map(option => `<option ${String(option) === String(value) ? 'selected' : ''}>${option}</option>`).join('')}</select>` : `<input value="${value}">`}<small>${help}</small></label>`).join('')}</div>${button('恢复默认值', 'restore-advanced')}`;
  if (item.tuning === 'grid') { const options = app.querySelector('.tuning-options'); const basic = gridParameters(item.type); options?.insertAdjacentHTML('afterend', `<div class="grid-settings"><div class="panel-head"><div><h3>网格候选值</h3><p>可直接增删逗号分隔的候选值。</p><b data-grid-count></b></div>${button('恢复推荐值', 'restore-grid')}</div>${basic.slice(0, 3).map(([name, values]) => `<label><span>${name}</span><input data-grid-values value="${values}"></label>`).join('')}<details><summary>更多调参参数</summary>${advanced.slice(0, 4).map(([name, value, help]) => `<label class="grid-extra"><input type="checkbox"><span>${name}<small>${help}</small></span><input data-grid-values value="${value}" disabled></label>`).join('')}</details></div>`); const settings = app.querySelector('.grid-settings'); if (settings) gridCountV6(settings); }
};

trainingPanel = function () {
  if (state.training.minimized) return `<div class="training-mini"><div class="training-stage"><b>${state.training.label}</b><span>${state.training.progress}%</span></div><div class="progress"><i style="width:${state.training.progress}%"></i></div><div class="row-actions">${button('展开', 'expand-training')}${button('取消', 'cancel-training')}</div></div>`;
  return `<div class="training-overlay"><div class="training-dialog"><div class="panel-head"><div><h2>模型训练中</h2><p>当前为模拟训练，结果用于展示前端流程。</p></div><button data-action="minimize-training">最小化</button></div><div class="training-stage"><b>${state.training.label}</b><span>${state.training.progress}%</span></div><div class="progress"><i style="width:${state.training.progress}%"></i></div>${button('取消训练', 'cancel-training')}</div></div>`;
};

function baseResultValueV6(result, key) {
  if (key === 'precision') return +(result.f1 * result.recall / Math.max(.01, 2 * result.recall - result.f1)).toFixed(3); return result[key];
}

function resultValueV6(result, key, scope) {
  const base = baseResultValueV6(result, key); if (scope === 'validation' || key === 'gap') return base; const lower = ['rmse', 'mae'].includes(key); const value = lower ? base - result.gap : base + result.gap; return +Math.max(0, value).toFixed(3);
}

sortedExperimentResults = function (item) {
  const valid = project().task === 'regression' ? ['rmse', 'mae', 'r2', 'gap'] : ['auc', 'ks', 'f1', 'accuracy', 'precision', 'recall', 'gap']; const key = valid.includes(state.tuningSort) ? state.tuningSort : valid[0]; const ascending = ['rmse', 'mae', 'gap'].includes(key); return [...item.results].sort((first, second) => ascending ? resultValueV6(first, key, state.resultScope) - resultValueV6(second, key, state.resultScope) : resultValueV6(second, key, state.resultScope) - resultValueV6(first, key, state.resultScope));
};

tuningPage = function () {
  const item = experiment(); if (!item?.results?.length) return shell(`${steps('tuning')}${pageHead('训练结果', '完成模型训练后查看结果。')}<div class="empty-state"><h2>还没有结果</h2>${button('返回模型训练', 'go-experiment', 'primary')}</div>`); const regression = project().task === 'regression'; const options = regression ? [['rmse', 'RMSE'], ['mae', 'MAE'], ['r2', 'R²'], ['gap', '训练/验证差值']] : [['auc', 'AUC'], ['ks', 'KS'], ['f1', 'F1'], ['accuracy', '准确率'], ['precision', '精确率'], ['recall', '召回率'], ['gap', '训练/验证差值']]; if (!options.some(option => option[0] === state.tuningSort)) state.tuningSort = options[0][0]; const validIds = item.results.map(result => result.id); const currentSelection = (state.tuningSelections[item.id] || []).filter(id => validIds.includes(id)); state.tuningSelections[item.id] = currentSelection.length ? currentSelection : [sortedExperimentResults(item)[0].id]; const rows = state.showAllResults ? sortedExperimentResults(item) : sortedExperimentResults(item).slice(0, 3);
  return shell(`${steps('tuning')}${pageHead('训练结果', `${esc(project().name)} / ${esc(dataset().name)} / ${esc(item.name)}`, button(state.showAllResults ? '仅看 Top 3' : '查看全部结果', 'toggle-results'))}<div class="tuning-toolbar"><label>数据范围<select data-result-scope><option value="validation" ${state.resultScope === 'validation' ? 'selected' : ''}>验证集</option><option value="train" ${state.resultScope === 'train' ? 'selected' : ''}>训练集</option></select></label><label>排序指标<select data-tuning-sort>${options.map(option => `<option value="${option[0]}" ${(state.tuningSort || options[0][0]) === option[0] ? 'selected' : ''}>${option[1]}</option>`).join('')}</select></label><span>默认按验证集指标排序</span></div><div class="table-card"><table class="result-table"><thead><tr><th>保存</th><th>排名</th><th>参数方案</th>${regression ? '<th>训练 RMSE</th><th>验证 RMSE</th><th>训练 MAE</th><th>验证 MAE</th><th>验证 R²</th>' : '<th>训练 AUC</th><th>验证 AUC</th><th>训练 KS</th><th>验证 KS</th><th>验证 F1</th>'}<th>差值</th><th>操作</th></tr></thead><tbody>${rows.map((result, index) => `<tr><td><input type="checkbox" data-save-result="${result.id}"></td><td><b>#${index + 1}</b></td><td>${result.params}</td>${regression ? `<td>${resultValueV6(result, 'rmse', 'train')}</td><td>${result.rmse}</td><td>${resultValueV6(result, 'mae', 'train')}</td><td>${result.mae}</td><td>${result.r2}</td>` : `<td>${resultValueV6(result, 'auc', 'train')}</td><td>${result.auc}</td><td>${resultValueV6(result, 'ks', 'train')}</td><td>${result.ks}</td><td>${result.f1}</td>`}<td>${result.gap}</td><td>${button('查看模型报告', `report-result:${result.id}`, 'primary')}</td></tr>`).join('')}</tbody></table></div><div class="save-note"><b>默认勾选当前排序下第 1 名，可多选其他结果。</b><span>保存后将跳转到模型库。</span>${button('保存所选结果到模型库', 'save-library-results', 'primary')}</div>`);
};

const previousReportPageV6 = reportPage;
reportPage = function () {
  const item = experiment(); const result = item.results.find(row => row.id === item.selected) || item.results[0]; const regression = project().task === 'regression'; const key = regression ? 'rmse' : 'auc'; const label = regression ? 'RMSE' : 'AUC'; const validation = result[key]; const train = resultValueV6(result, key, 'train');
  let content = previousReportPageV6().replace('返回调参结果', '返回训练结果').replace('<div class="report-hero">', `<div class="report-comparison"><div><span>训练集 ${label}</span><b>${train}</b><small>${regression ? '越小越好' : '越大越好'}</small></div><div><span>验证集 ${label}</span><b>${validation}</b><small>用于模型排名</small></div><div><span>训练 / 验证差值</span><b>${result.gap}</b><small>越小通常越稳定</small></div></div><div class="report-hero">`);
  if (!regression) { const total = 1000; const positives = 265; const recall = result.recall; const truePositive = Math.round(positives * recall); const falseNegative = positives - truePositive; const precision = Math.min(.99, result.f1 * recall / Math.max(.01, 2 * recall - result.f1)); const falsePositive = Math.max(1, Math.round(truePositive / precision - truePositive)); const trueNegative = total - positives - falsePositive; const accuracy = +((truePositive + trueNegative) / total).toFixed(3); const computedPrecision = +(truePositive / (truePositive + falsePositive)).toFixed(3); const computedRecall = +(truePositive / (truePositive + falseNegative)).toFixed(3); const computedF1 = +(2 * computedPrecision * computedRecall / (computedPrecision + computedRecall)).toFixed(3); const block = `<section class="classification-evaluation"><div class="section-title"><h2>分类评估</h2><span>基于验证集混淆矩阵计算</span></div><div class="metrics-grid"><div class="metric-card"><span>准确率</span><b>${accuracy}</b><small>(TP + TN) / 全部样本</small></div><div class="metric-card"><span>精确率</span><b>${computedPrecision}</b><small>TP / (TP + FP)</small></div><div class="metric-card"><span>召回率</span><b>${computedRecall}</b><small>TP / (TP + FN)</small></div><div class="metric-card"><span>F1</span><b>${computedF1}</b><small>2 × 精确率 × 召回率 / 两者之和</small></div></div><div class="confusion-card"><h3>混淆矩阵</h3><table class="confusion-matrix"><thead><tr><th></th><th>预测正类</th><th>预测负类</th></tr></thead><tbody><tr><th>实际正类</th><td><b>${truePositive}</b><small>TP</small></td><td><b>${falseNegative}</b><small>FN</small></td></tr><tr><th>实际负类</th><td><b>${falsePositive}</b><small>FP</small></td><td><b>${trueNegative}</b><small>TN</small></td></tr></tbody></table></div></section>`; content = content.replace('<section class="section-block">', `${block}<section class="section-block">`); }
  return content;
};

function globalLibraryRowsV6() {
  return Object.values(state.experiments).filter(item => item.results?.length && (state.libraryProjectId === 'all' || item.projectId === state.libraryProjectId) && (state.libraryDatasetId === 'all' || item.datasetId === state.libraryDatasetId) && (state.libraryModelType === 'all' || item.type === state.libraryModelType)).flatMap(item => item.results.filter(result => (state.savedResults[item.id] || []).includes(result.id)).map(result => ({ item, result })));
}

modelsPage = function () {
  const projectIds = state.libraryProjectId === 'all' ? state.projects.map(item => item.id) : [state.libraryProjectId]; const datasets = projectIds.flatMap(projectId => state.projects.find(item => item.id === projectId)?.datasets || []).map(id => state.datasets[id]).filter(Boolean); const types = [...new Set(Object.values(state.experiments).filter(item => projectIds.includes(item.projectId) && (state.libraryDatasetId === 'all' || item.datasetId === state.libraryDatasetId)).map(item => item.type))]; const rows = globalLibraryRowsV6();
  const compare = `<div class="library-toolbar"><label>项目<select data-v6-library-project><option value="all">全部项目</option>${state.projects.map(item => `<option value="${item.id}" ${item.id === state.libraryProjectId ? 'selected' : ''}>${esc(item.name)}</option>`).join('')}</select></label><label>数据集<select data-v6-library-dataset><option value="all">全部数据集</option>${datasets.map(item => `<option value="${item.id}" ${item.id === state.libraryDatasetId ? 'selected' : ''}>${esc(item.name)}</option>`).join('')}</select></label><label>模型类型<select data-v6-library-type><option value="all">全部模型</option>${types.map(type => `<option value="${type}" ${type === state.libraryModelType ? 'selected' : ''}>${modelName(type)}</option>`).join('')}</select></label></div>${rows.length ? `<div class="table-card"><table><thead><tr><th>项目</th><th>数据集</th><th>模型实验</th><th>模型类型</th><th>参数方案</th><th>核心指标</th><th>操作</th></tr></thead><tbody>${rows.map(({ item, result }) => { const owner = state.projects.find(projectItem => projectItem.id === item.projectId); const set = state.datasets[item.datasetId]; const regression = owner.task === 'regression'; return `<tr><td>${esc(owner.name)}</td><td>${esc(set.name)}</td><td><b>${esc(item.name)}</b></td><td>${modelName(item.type)}</td><td>${result.params}</td><td>${regression ? `RMSE ${result.rmse} · R² ${result.r2}` : `AUC ${result.auc} · KS ${result.ks}`}</td><td><div class="row-actions">${button('查看训练结果', `library-result:${item.id}:${result.id}`)}${button('生成 API 配置', `open-api-config:${item.id}:${result.id}`)}</div></td></tr>`; }).join('')}</tbody></table></div>` : '<div class="empty-state"><h2>当前筛选范围暂无已保存结果</h2><p>请在训练结果页面保存至少一组参数方案。</p></div>'}`;
  const services = `<div class="table-card"><table><thead><tr><th>服务名称</th><th>绑定模型</th><th>参数方案</th><th>创建时间</th><th>状态</th><th>操作</th></tr></thead><tbody>${state.apiConfigs.length ? state.apiConfigs.map(config => { const item = state.experiments[config.experimentId]; return `<tr><td><b>${esc(config.name)}</b></td><td>${esc(item?.name || '模型已删除')}</td><td>#${config.resultId}</td><td>${config.createdAt}</td><td><span class="status good">演示配置</span></td><td><div class="row-actions">${item ? button('查看接入说明', `view-api-config:${config.id}`) : ''}${button('删除', `delete-api-config:${config.id}`)}</div></td></tr>`; }).join('') : '<tr><td colspan="6"><div class="empty-state"><p>尚未生成 API 接入配置。</p></div></td></tr>'}</tbody></table></div>`;
  return shell(`${pageHead('模型库', '跨项目查看已保存模型结果，并管理演示 API 接入配置。')}<div class="library-tabs"><button data-action="library-tab:compare" class="${state.libraryTab === 'compare' ? 'active' : ''}">模型比较</button><button data-action="library-tab:api" class="${state.libraryTab === 'api' ? 'active' : ''}">API 服务</button></div>${state.libraryTab === 'api' ? services : compare}`);
};

enhanceModelsPage = function () {};

deleteModal = function (type, id) {
  const labels = { project: ['项目', '其下所有数据集、模型和 API 配置'], dataset: ['数据集', '其下所有模型和 API 配置'], model: ['模型', '其训练结果、模型库结果和 API 配置'] }; const label = labels[type];
  modal(`<h2>删除${label[0]}</h2><p>删除后无法恢复，${label[1]}也会同时删除。</p><div class="modal-actions">${button('取消', 'close-modal')}${button('确认删除', `delete-entity:${type}:${id}`, 'primary')}</div>`); const confirm = document.querySelector('[data-action^="delete-entity:"]'); confirm.onclick = event => { event.stopPropagation(); action(confirm.dataset.action); };
};

function enhanceFlowActionsV6() {
  const returnActions = ['go-projects', 'go-project', 'go-dataset', 'go-experiments', 'go-tuning', 'go-models']; returnActions.forEach(actionName => app.querySelectorAll(`.page-head [data-action="${actionName}"]`).forEach(element => element.remove())); let left = ''; let right = '';
  if (state.page === 'project') left = button('返回项目列表', 'go-projects');
  if (state.page === 'dataset') { app.querySelector('[data-action="go-feature"]')?.remove(); left = button('返回项目', 'go-project'); right = button('下一步：特征准备', 'go-feature-v6', 'primary'); }
  if (state.page === 'feature') { app.querySelector('[data-action="go-experiments"]')?.remove(); app.querySelector('[data-action="next-feature"]')?.remove(); if (state.featureStep === 0) { left = button('返回数据检查', 'go-dataset'); right = button('下一步：特征管理', 'next-feature', 'primary'); } else { left = button('返回训练集划分', 'back-feature-split'); right = button('下一步：模型训练', 'go-experiments', 'primary'); } }
  if (state.page === 'experiments') left = button('返回数据集', 'go-dataset');
  if (state.page === 'model-select') left = button('返回模型实验', 'go-experiments');
  if (state.page === 'experiment') { app.querySelector('[data-action="train"]')?.remove(); left = button('返回模型实验', 'go-experiments'); right = experiment()?.status === 'completed' ? button('进入训练结果', 'go-tuning', 'primary') : button('开始训练', 'train', 'primary'); }
  if (state.page === 'tuning') left = button('返回模型训练', 'go-experiment');
  if (state.page === 'report') left = button('返回训练结果', 'go-tuning');
  if (state.page === 'api') left = button('返回模型库', 'go-models');
  if (left || right) app.querySelector('.page')?.insertAdjacentHTML('beforeend', `<div class="flow-footer"><div>${left}</div><div>${right}</div></div>`);
}

let trainingRunV6 = 0;
startTraining = function () {
  const item = experiment(); const run = ++trainingRunV6; item.status = 'training'; state.training = { progress: 8, label: '正在校验配置', minimized: false }; render(); const stages = [[28, '正在准备数据'], [52, item.tuning === 'auto' ? '正在快速自动调参' : '正在训练模型'], [78, '正在计算训练集与验证集指标'], [100, '正在生成训练结果']]; let index = 0;
  const timer = setInterval(() => { if (run !== trainingRunV6) return clearInterval(timer); state.training = { ...state.training, progress: stages[index][0], label: stages[index][1] }; render(); index += 1; if (index === stages.length) { clearInterval(timer); setTimeout(() => { if (run !== trainingRunV6) return; const count = item.tuning === 'none' ? 1 : item.tuning === 'auto' ? 3 : 8; item.results = makeResults(project().task, count); item.selected = 1; item.status = 'completed'; item.updatedAt = now(); state.training = null; save(); go('tuning'); }, 350); } }, 650);
};

action = function (name) {
  if (name === 'go-projects') return go('projects'); if (name === 'go-project') return go('project'); if (name === 'go-dataset') return go('dataset'); if (name === 'go-models') return go('models');
  if (name.startsWith('enter-dataset:')) { state.datasetId = name.split(':')[1]; state.experimentId = dataset().experiments[0]; save(); return go('dataset'); }
  if (name.startsWith('enter-experiments:')) { state.datasetId = name.split(':')[1]; state.experimentId = dataset().experiments[0]; save(); return go('experiments'); }
  if (name === 'go-feature-v6') { state.featureStep = 0; save(); return go('feature'); }
  if (name === 'back-feature-split') { state.featureStep = 0; save(); return render(); }
  if (name === 'recommend-thresholds') { document.querySelectorAll('[data-threshold]').forEach(input => input.value = recommendedThresholdsV6[input.dataset.threshold]); return toast('已填入系统推荐阈值，可继续修改。'); }
  if (name === 'auto-filter-v6') { const values = recommendedThresholdsV6; dataset().columns.forEach(column => { if (!column.target && column.trainable) column.included = column.missing * 100 <= values.missing && (column.psi ?? 0) <= values.psi && (project().task !== 'classification' || (column.iv ?? 1) >= values.iv); }); const trainable = dataset().columns.filter(column => !column.target && column.trainable); const included = trainable.filter(column => column.included).length; const excluded = trainable.length - included; dataset().feature.revision += 1; markDatasetStale(); save(); render(); return toast(`自动筛选完成：纳入 ${included} 个，排除 ${excluded} 个。`); }
  if (name === 'confirm-thresholds') { const values = state.featureThresholds; document.querySelectorAll('[data-threshold]').forEach(input => values[input.dataset.threshold] = +input.value); dataset().columns.forEach(column => { if (!column.target && column.trainable) column.included = column.missing * 100 <= values.missing && (column.psi ?? 0) <= values.psi && (project().task !== 'classification' || (column.iv ?? 1) >= values.iv); }); dataset().feature.revision += 1; markDatasetStale(); save(); render(); return toast('已按当前阈值更新特征。'); }
  if (name === 'confirm-correlation-threshold') { const input = document.querySelector('[data-correlation-draft]'); const value = +input.value; if (Number.isNaN(value) || value < 0 || value > 1) return toast('相关性阈值必须在 0–1 之间。'); state.featureThresholds.correlation = value; save(); render(); return toast('相关性预警阈值已更新。'); }
  if (name === 'preview-correlation') { const pairs = correlationValuesV6().pairs.filter(pair => pair.score >= state.featureThresholds.correlation); if (!pairs.length) return toast('当前没有需要处理的高相关特征。'); state.pendingCorrelationExclusions = pairs.map(pair => pair.first.missing <= pair.second.missing ? pair.second.name : pair.first.name); modal(`<h2>自动处理高相关特征</h2><p>根据当前数据和已确认阈值生成以下建议，确认后才会修改纳入开关。</p><div class="table-card"><table><thead><tr><th>保留字段</th><th>排除字段</th><th>相关系数</th><th>推荐理由</th></tr></thead><tbody>${pairs.map(pair => { const keep = pair.first.missing <= pair.second.missing ? pair.first : pair.second; const exclude = keep === pair.first ? pair.second : pair.first; return `<tr><td>${esc(keep.name)}</td><td>${esc(exclude.name)}</td><td>${pair.score}</td><td>${keep.missing < exclude.missing ? '缺失率更低' : '筛选指标更优或更稳定'}</td></tr>`; }).join('')}</tbody></table></div><div class="modal-actions">${button('取消', 'close-modal')}${button('确认处理', 'confirm-correlation-v6', 'primary')}</div>`); document.querySelector('[data-action="confirm-correlation-v6"]').onclick = event => { event.stopPropagation(); action('confirm-correlation-v6'); }; return; }
  if (name === 'confirm-correlation-v6') { dataset().columns.forEach(column => { if ((state.pendingCorrelationExclusions || []).includes(column.name)) column.included = false; }); state.pendingCorrelationExclusions = []; document.querySelector('.modal-backdrop')?.remove(); save(); render(); return toast('已按当前数据处理高相关特征。'); }
  if (name === 'save-library-results') { const item = experiment(); const selected = state.tuningSelections[item.id] || []; if (!selected.length) return toast('请至少选择一个结果。'); state.savedResults[item.id] = [...new Set([...(state.savedResults[item.id] || []), ...selected])]; state.libraryProjectId = 'all'; state.libraryDatasetId = 'all'; state.libraryModelType = 'all'; state.libraryTab = 'compare'; save(); return go('models'); }
  if (name === 'minimize-training') { state.training.minimized = true; return render(); } if (name === 'expand-training') { state.training.minimized = false; return render(); } if (name === 'cancel-training') { trainingRunV6 += 1; experiment().status = 'draft'; state.training = null; save(); render(); return toast('训练已取消。'); }
  if (name === 'project-models') { state.libraryProjectId = project().id; state.libraryDatasetId = 'all'; state.libraryTab = 'compare'; return go('models'); }
  return previousActionV6(name);
};

bind = function () {
  previousBindV6(); enhanceFlowActionsV6(); app.querySelectorAll('[data-action]').forEach(element => element.onclick = event => { event.stopPropagation(); action(element.dataset.action); });
  app.querySelectorAll('[data-grid-values]').forEach(input => input.addEventListener('input', () => gridCountV6(input.closest('.grid-settings')))); app.querySelectorAll('.grid-extra>input[type="checkbox"]').forEach(checkbox => checkbox.addEventListener('change', () => { const input = checkbox.parentElement.querySelector('[data-grid-values]'); input.disabled = !checkbox.checked; gridCountV6(checkbox.closest('.grid-settings')); }));
  const sort = document.querySelector('[data-tuning-sort]'); if (sort) { const clean = sort.cloneNode(true); sort.replaceWith(clean); clean.onchange = event => { state.tuningSort = event.target.value; const item = experiment(); if ((state.tuningSelections[item.id] || []).length <= 1) state.tuningSelections[item.id] = [sortedExperimentResults(item)[0].id]; save(); render(); }; }
  document.querySelector('[data-result-scope]')?.addEventListener('change', event => { state.resultScope = event.target.value; const item = experiment(); if ((state.tuningSelections[item.id] || []).length <= 1) state.tuningSelections[item.id] = [sortedExperimentResults(item)[0].id]; save(); render(); });
  document.querySelector('[data-correlation-draft]')?.addEventListener('input', event => { const note = document.querySelector('[data-correlation-unsaved]'); if (note) note.hidden = +event.target.value === state.featureThresholds.correlation; });
  document.querySelector('[data-v6-library-project]')?.addEventListener('change', event => { state.libraryProjectId = event.target.value; state.libraryDatasetId = 'all'; save(); render(); }); document.querySelector('[data-v6-library-dataset]')?.addEventListener('change', event => { state.libraryDatasetId = event.target.value; save(); render(); }); document.querySelector('[data-v6-library-type]')?.addEventListener('change', event => { state.libraryModelType = event.target.value; save(); render(); });
};

render();
