const app = document.querySelector('#app');
const fileInput = document.querySelector('#file-input');
const now = () => new Date().toLocaleString('zh-CN', { hour12: false });
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const uid = prefix => `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2, 6)}`;
const modelCatalog = {
  classification: [
    ['logistic', '逻辑回归', '稳定、易解释，适合作为分类基线。'], ['tree', '决策树分类', '规则直观，适合解释非线性关系。'],
    ['forest', '随机森林分类', '多棵树投票，效果稳定。'], ['knn', 'KNN 分类', '根据相似样本完成分类。'], ['lgbm', 'LGBM 分类', '训练速度快，适合结构化数据。']
  ],
  regression: [
    ['linear', '线性回归', '简单易解释的回归基线。'], ['regtree', '决策树回归', '通过分支规则预测连续值。'],
    ['regforest', '随机森林回归', '多棵树共同预测，稳定性较好。'], ['lgbmreg', 'LGBM 回归', '适合结构化数据的高效提升模型。']
  ]
};
const modelName = type => Object.values(modelCatalog).flat().find(item => item[0] === type)?.[1] || type;
const exampleColumns = {
  churn: [
    { name: '客户编号', type: 'text', missing: 0, unique: 7043, trainable: false, reason: '疑似 ID，唯一值接近样本数', iv: .002, psi: .03, included: false },
    { name: '合同月数', type: 'number', missing: 0, unique: 73, trainable: true, iv: .31, psi: .08, included: true },
    { name: '月费用', type: 'number', missing: 0, unique: 1585, trainable: true, iv: .18, psi: .12, included: true },
    { name: '套餐类型', type: 'category', missing: .02, unique: 4, trainable: true, iv: .12, psi: .06, included: true },
    { name: '注册日期', type: 'date', missing: 0, unique: 2180, trainable: false, reason: '原始日期字段', iv: 0, psi: .04, included: false },
    { name: '是否流失', type: 'category', missing: 0, unique: 2, trainable: true, target: true, included: false }
  ],
  housing: [
    { name: '房源编号', type: 'text', missing: 0, unique: 1460, trainable: false, reason: '疑似 ID，唯一值接近样本数', iv: 0, psi: .03, included: false },
    { name: '面积', type: 'number', missing: 0, unique: 832, trainable: true, iv: .28, psi: .08, included: true },
    { name: '卧室数', type: 'number', missing: .01, unique: 8, trainable: true, iv: .14, psi: .05, included: true },
    { name: '建造年份', type: 'number', missing: 0, unique: 112, trainable: true, iv: .19, psi: .11, included: true },
    { name: '房价', type: 'number', missing: 0, unique: 1320, trainable: true, target: true, included: false }
  ]
};
const previews = {
  churn: [
    ['C-0001', 1, 29.85, '基础套餐', '2024-01-05', '否'], ['C-0002', 34, 56.95, '家庭套餐', '2021-08-19', '否'],
    ['C-0003', 2, 53.85, '基础套餐', '2025-03-11', '是'], ['C-0004', 45, 42.30, '高级套餐', '2020-06-28', '否']
  ],
  housing: [['H-001', 1710, 3, 2003, 208500], ['H-002', 1262, 3, 1976, 181500], ['H-003', 1786, 3, 2001, 223500], ['H-004', 1717, 4, 1915, 140000]]
};
function initialState() {
  const projects = [
    { id: 'p-churn', name: '客户流失分析', task: 'classification', createdAt: '2026/8/20 10:20:00', updatedAt: now(), datasets: ['d-churn'] },
    { id: 'p-house', name: '房价预测研究', task: 'regression', createdAt: '2026/8/21 14:35:00', updatedAt: now(), datasets: ['d-house'] }
  ];
  const datasets = {
    'd-churn': { id: 'd-churn', projectId: 'p-churn', name: '客户流失样本', uploadedAt: '2026/8/20 10:28:00', rows: 7043, target: '是否流失', positive: '是', columns: exampleColumns.churn, preview: previews.churn, feature: { missing: 'median', split: '80-20', revision: 1 }, experiments: ['e-lgbm'] },
    'd-house': { id: 'd-house', projectId: 'p-house', name: '住宅价格数据', uploadedAt: '2026/8/21 14:41:00', rows: 1460, target: '房价', columns: exampleColumns.housing, preview: previews.housing, feature: { missing: 'median', split: '80-20', revision: 1 }, experiments: ['e-reg'] }
  };
  const experiments = {
    'e-lgbm': { id: 'e-lgbm', projectId: 'p-churn', datasetId: 'd-churn', name: 'LGBM 分类 01', type: 'lgbm', standardize: false, tuning: 'auto', status: 'completed', updatedAt: now(), results: makeResults('classification', 8), selected: 1 },
    'e-reg': { id: 'e-reg', projectId: 'p-house', datasetId: 'd-house', name: '随机森林回归 01', type: 'regforest', standardize: false, tuning: 'grid', status: 'completed', updatedAt: now(), results: makeResults('regression', 7), selected: 1 }
  };
  return { page: 'home', projectId: 'p-churn', datasetId: 'd-churn', experimentId: 'e-lgbm', projects, datasets, experiments, previewTab: 'overview', showAllResults: false, featureStep: 0, training: null };
}
function makeResults(task, count) {
  return Array.from({ length: count }, (_, index) => task === 'classification' ? {
    id: index + 1, params: `树 ${100 + index * 25} · 学习率 ${(0.03 + index * .01).toFixed(2)}`, auc: +(.903 - index * .006).toFixed(3), ks: +(.64 - index * .012).toFixed(2), f1: +(.79 - index * .009).toFixed(2), accuracy: +(.90 - index * .005).toFixed(2), recall: +(.82 - index * .01).toFixed(2), gap: +(.014 + index * .005).toFixed(3)
  } : {
    id: index + 1, params: `树 ${120 + index * 30} · 深度 ${6 + index % 4}`, rmse: +(3.42 + index * .13).toFixed(2), mae: +(2.31 + index * .09).toFixed(2), r2: +(.84 - index * .012).toFixed(3), gap: +(.18 + index * .04).toFixed(2)
  });
}
let state;
try { state = JSON.parse(localStorage.getItem('mlStudioV3')) || initialState(); } catch { state = initialState(); }
const defaultState = initialState();
if (!state || typeof state !== 'object' || Array.isArray(state)) state = defaultState;
state.projects = Array.isArray(state.projects) ? state.projects : defaultState.projects;
state.datasets = state.datasets && typeof state.datasets === 'object' && !Array.isArray(state.datasets) ? state.datasets : defaultState.datasets;
state.experiments = state.experiments && typeof state.experiments === 'object' && !Array.isArray(state.experiments) ? state.experiments : defaultState.experiments;
if (!state.projects.length && !['home', 'projects'].includes(state.page)) state.page = 'home';
function save() {
  try { localStorage.setItem('mlStudioV3', JSON.stringify(state)); }
  catch (error) { console.warn('本地保存不可用，页面将继续使用当前会话数据。', error); }
}
function project() { return state.projects.find(item => item.id === state.projectId) || state.projects[0]; }
function dataset() { return state.datasets[state.datasetId] || state.datasets[project()?.datasets?.[0]]; }
function experiment() { return state.experiments[state.experimentId] || state.experiments[dataset()?.experiments?.[0]]; }
function taskLabel(task) { return task === 'regression' ? '回归' : '二分类'; }
function statusLabel(status) { return ({ completed: '已完成', stale: '需要重新训练', draft: '草稿', training: '训练中', cancelled: '已取消' }[status] || status); }
function markDatasetStale(set = dataset()) { set.experiments.forEach(id => { if (state.experiments[id]?.status === 'completed') state.experiments[id].status = 'stale'; }); }
function go(page) { state.page = page; save(); render(); }
function button(label, action, className = '') { return `<button class="btn ${className}" data-action="${action}">${label}</button>`; }
function sidebar() {
  return `<aside class="sidebar"><div class="brand"><span>M</span><b>ML Studio</b></div><nav class="main-nav"><button data-page="home" class="${state.page === 'home' ? 'active' : ''}">⌂ 首页</button><button data-page="projects" class="${['projects', 'project', 'dataset', 'feature', 'experiments', 'experiment', 'tuning', 'report'].includes(state.page) ? 'active' : ''}">▣ 项目</button><button data-page="models" class="${state.page === 'models' ? 'active' : ''}">◇ 模型库</button></nav><div class="sidebar-section"><div class="sidebar-title"><span>项目</span><button data-action="new-project">＋</button></div>${state.projects.map(item => `<div class="project-link ${item.id === state.projectId ? 'selected' : ''}"><button class="project-main" data-project="${item.id}"><span>${item.task === 'regression' ? 'R' : 'C'}</span><b>${esc(item.name)}</b></button><div class="project-popover" data-popover="${item.id}">${projectPopover(item)}</div></div>`).join('')}</div><div class="beginner-note"><b>初学者模式</b><span>按固定步骤完成训练，无需编写代码。</span></div></aside>`;
}
function projectPopover(item) {
  const sets = item.datasets.map(id => state.datasets[id]).filter(Boolean); const selected = sets[0];
  return `<div class="popover-tabs"><button data-pop-tab="overview" class="active">项目概览</button><button data-pop-tab="metrics">数据集指标</button><button data-pop-tab="preview">数据预览</button></div><div class="popover-panel active" data-pop-panel="overview"><strong>${esc(item.name)}</strong><p>${taskLabel(item.task)} · 创建于 ${item.createdAt}</p><div class="popover-stats"><span><b>${sets.length}</b> 数据集</span><span><b>${sets.reduce((sum, set) => sum + set.experiments.length, 0)}</b> 模型实验</span></div></div><div class="popover-panel" data-pop-panel="metrics">${sets.length ? sets.map(set => `<div class="popover-dataset"><b>${esc(set.name)}</b><span>${set.rows.toLocaleString()} 行 · ${set.columns.length} 列 · 目标：${set.target}</span></div>`).join('') : '<p>还没有数据集</p>'}</div><div class="popover-panel" data-pop-panel="preview">${selected ? `<small>当前仅预览前 150 行 · 第 1 页 / 共 8 页</small><div class="mini-preview">${selected.preview.slice(0, 3).map(row => `<div>${row.slice(0, 3).map(value => `<span>${esc(value)}</span>`).join('')}</div>`).join('')}</div>` : '<p>还没有可预览的数据</p>'}</div>`;
}
function shell(content) { return `<div class="app-shell">${sidebar()}<main><header class="topbar"><div><span>项目</span><b>${esc(project()?.name || '未选择项目')}</b></div><div class="top-actions"><span class="mock">模拟结果</span><span class="saved">● 已本地保存</span><span class="avatar">ML</span></div></header><section class="page">${content}</section></main></div><div id="toast" class="toast"></div>`; }
function pageHead(title, subtitle, actions = '') { return `<div class="page-head"><div><h1>${title}</h1><p>${subtitle}</p></div><div class="head-actions">${actions}</div></div>`; }
function homePage() {
  return shell(`${pageHead('零代码训练你的机器学习模型', '从项目开始，按固定步骤完成数据检查、特征工程、训练和解释。', button('＋ 创建项目', 'new-project', 'primary'))}<div class="hero-grid"><div class="hero-card"><span class="eyebrow">固定流程 · 更适合初学者</span><h2>项目、数据集和模型实验<br>都在一个平台中管理</h2><p>不再使用自由画布。系统只展示当前任务需要的模型和配置。</p><div class="flow-strip"><span>1 数据检查</span><i>→</i><span>2 特征工程</span><i>→</i><span>3 模型实验</span><i>→</i><span>4 查看结果</span></div></div><div class="hero-side"><b>当前工作区</b><strong>${state.projects.length}</strong><span>个项目</span><strong>${Object.keys(state.experiments).length}</strong><span>个模型实验</span></div></div><div class="section-title"><h2>最近项目</h2><span>所有数据只保存在当前浏览器</span></div><div class="card-grid">${state.projects.map(projectCard).join('')}</div>`);
}
function projectCard(item) { const sets = item.datasets.map(id => state.datasets[id]).filter(Boolean); return `<article class="card project-card" data-open-project="${item.id}"><div class="card-top"><span class="task-badge ${item.task}">${taskLabel(item.task)}</span><span>${item.createdAt.split(' ')[0]}</span></div><h3>${esc(item.name)}</h3><p>${sets.length} 个数据集 · ${sets.reduce((sum, set) => sum + set.experiments.length, 0)} 个模型实验</p><button class="text-link">打开项目 →</button></article>`; }
function projectsPage() { return shell(`${pageHead('项目', '按项目管理数据集、模型实验和训练结果。', button('＋ 创建项目', 'new-project', 'primary'))}<div class="card-grid">${state.projects.map(projectCard).join('')}</div>`); }
function projectPage() {
  const current = project(); const sets = current.datasets.map(id => state.datasets[id]).filter(Boolean);
  return shell(`${pageHead(esc(current.name), `${taskLabel(current.task)}项目 · 创建于 ${current.createdAt}`, `${button('查看本项目模型', 'project-models')}${button('＋ 上传数据集', 'upload-dataset', 'primary')}`)}<div class="stats-grid"><div class="stat"><span>数据集</span><b>${sets.length}</b></div><div class="stat"><span>模型实验</span><b>${sets.reduce((sum, set) => sum + set.experiments.length, 0)}</b></div><div class="stat"><span>已完成模型</span><b>${sets.flatMap(set => set.experiments).filter(id => state.experiments[id]?.status === 'completed').length}</b></div></div><div class="section-title"><h2>数据集</h2><span>同一数据集下的模型共享目标列和特征配置</span></div><div class="dataset-list">${sets.map(set => `<article class="dataset-card" data-open-dataset="${set.id}"><div class="dataset-icon">▦</div><div><h3>${esc(set.name)}</h3><p>${set.rows.toLocaleString()} 行 · ${set.columns.length} 列 · 目标：${esc(set.target)}</p><span>上传于 ${set.uploadedAt}</span></div><div class="dataset-status"><b>${set.experiments.length}</b><span>模型实验</span></div><button class="btn">进入数据集</button></article>`).join('')}</div>`);
}
function steps(active) { const labels = [['dataset', '数据检查'], ['feature', '特征工程'], ['experiments', '模型实验'], ['tuning', '调参结果'], ['report', '模型报告']]; const activeIndex = labels.findIndex(item => item[0] === active); return `<div class="stepper">${labels.map((item, index) => `<button data-page="${item[0]}" class="${index === activeIndex ? 'active' : index < activeIndex ? 'done' : ''}"><i>${index < activeIndex ? '✓' : index + 1}</i><span>${item[1]}</span></button>`).join('')}</div>`; }
function typeLabel(type) { return ({ number: '数值', category: '类别', date: '日期', boolean: '布尔', text: '文本' }[type] || type); }
function datasetPage() {
  const set = dataset(); const headers = set.columns.map(column => column.name);
  return shell(`${steps('dataset')}${pageHead('数据检查', `${esc(set.name)} · 当前仅预览前 150 行`, button('继续特征工程', 'go-feature', 'primary'))}<div class="stats-grid"><div class="stat"><span>数据量</span><b>${set.rows.toLocaleString()}</b><small>行</small></div><div class="stat"><span>字段数</span><b>${set.columns.length}</b><small>列</small></div><div class="stat"><span>目标列</span><b class="small-value">${esc(set.target)}</b></div><div class="stat"><span>不可训练字段</span><b>${set.columns.filter(column => !column.trainable && !column.target).length}</b></div></div><div class="section-title"><h2>字段类型检查</h2><span>风险字段只在此识别，最终特征在特征工程中管理</span></div><div class="table-card"><table><thead><tr><th>字段</th><th>确认类型</th><th>缺失率</th><th>唯一值</th><th>一致性</th><th>训练可用性</th></tr></thead><tbody>${set.columns.map((column, index) => `<tr><td><b>${esc(column.name)}</b>${column.target ? '<small>目标列</small>' : ''}</td><td><select data-column-type="${index}">${['number', 'category', 'date', 'boolean', 'text'].map(type => `<option value="${type}" ${type === column.type ? 'selected' : ''}>${typeLabel(type)}</option>`).join('')}</select></td><td>${(column.missing * 100).toFixed(1)}%</td><td>${column.unique.toLocaleString()}</td><td><span class="status good">类型一致</span></td><td>${column.target ? '<span class="status target">目标列</span>' : column.trainable ? '<span class="status good">可用于训练</span>' : `<span class="status blocked">不可用于训练</span><small>${esc(column.reason)}</small>`}</td></tr>`).join('')}</tbody></table></div><div class="section-title"><h2>数据预览</h2><span>每页 20 行，最多读取前 150 行</span></div><div class="table-card preview-table"><table><thead><tr>${headers.map(header => `<th>${esc(header)}</th>`).join('')}</tr></thead><tbody>${set.preview.map(row => `<tr>${row.map(value => `<td>${esc(value)}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="pagination"><button disabled>上一页</button><span>第 1 页 / 共 8 页</span><button>下一页</button></div></div>`);
}
function featurePage() {
  const set = dataset(); const trainable = set.columns.filter(column => !column.target);
  return shell(`${steps('feature')}${pageHead('特征工程', '按照固定顺序完成配置，步骤不能拖动或重新排序。', button('保存并进入模型实验', 'go-experiments', 'primary'))}<div class="feature-layout"><aside class="feature-nav">${['缺失值处理', '特征筛选', '标准化', '训练集划分'].map((label, index) => `<button data-feature-step="${index}" class="${state.featureStep === index ? 'active' : ''}"><i>${index + 1}</i><span>${label}</span>${index < state.featureStep ? '<b>✓</b>' : ''}</button>`).join('')}</aside><div class="feature-panel">${featureStepContent(set, trainable)}</div></div>`);
}
function featureStepContent(set, columns) {
  if (state.featureStep === 0) return `<div class="panel-head"><div><h2>缺失值处理</h2><p>数值字段默认使用中位数，不提供众数填充。</p></div><span class="status good">推荐配置</span></div><div class="option-grid"><label class="option-card selected"><input type="radio" checked><b>中位数填充</b><span>适用于数值字段，受极端值影响较小。</span></label><label class="option-card"><input type="radio"><b>删除所在行</b><span>只建议缺失比例非常低时使用。</span></label></div>${button('下一步：特征筛选', 'next-feature', 'primary')}`;
  if (state.featureStep === 1) return `<div class="panel-head"><div><h2>特征筛选</h2><p>自动推荐默认使用缺失率 ≤ 90%、IV ≥ 0.01。</p></div>${button('采用自动推荐', 'apply-feature')}</div><div class="threshold-row"><label>缺失率阈值 <input value="90%" disabled></label><label>IV 阈值 <input value="0.01" disabled></label><label>PSI 风险线 <input value="0.25" disabled></label><label>相关系数阈值 <input value="0.80" disabled></label></div><div class="table-card"><table><thead><tr><th>纳入</th><th>特征</th><th>类型</th><th>缺失率</th><th><span class="help" title="IV 衡量特征对目标的区分能力，通常越大越有用。">IV ⓘ</span></th><th><span class="help" title="PSI 衡量分布稳定性，数值过高表示稳定性风险。">PSI ⓘ</span></th><th>状态</th></tr></thead><tbody>${columns.map((column, index) => `<tr><td><label class="switch"><input type="checkbox" data-feature-toggle="${index}" ${column.included ? 'checked' : ''} ${!column.trainable ? 'disabled' : ''}><span></span></label></td><td><b>${esc(column.name)}</b>${column.reason ? `<small>${esc(column.reason)}</small>` : ''}</td><td>${typeLabel(column.type)}</td><td>${(column.missing * 100).toFixed(1)}%</td><td>${column.iv?.toFixed(3) ?? '—'}</td><td>${column.psi?.toFixed(2) ?? '—'}</td><td>${!column.trainable ? '<span class="status blocked">不可用于训练</span>' : column.included ? '<span class="status good">已纳入</span>' : '<span class="status muted">已排除</span>'}</td></tr>`).join('')}</tbody></table></div><div class="correlation-note"><b>高相关特征提示</b><span>合同月数与月费用 |r| = 0.85。系统推荐保留 IV 更高的合同月数。</span></div>${button('下一步：标准化', 'next-feature', 'primary')}`;
  if (state.featureStep === 2) return `<div class="panel-head"><div><h2>标准化</h2><p>标准化会在每个模型实验中根据模型自动设置，也允许手动覆盖。</p></div></div><div class="model-guidance"><div><b>默认开启</b><span>逻辑回归、KNN、线性回归</span></div><div><b>默认关闭</b><span>决策树、随机森林、LGBM</span></div></div><div class="notice">当前步骤无需统一选择。创建模型实验后，平台会显示该模型的推荐设置。</div>${button('下一步：训练集划分', 'next-feature', 'primary')}`;
  return `<div class="panel-head"><div><h2>训练集划分</h2><p>所有模型实验共享同一划分比例。</p></div><span class="status good">当前 80% / 20%</span></div><div class="ratio-grid">${['70-30', '75-25', '80-20', '90-10'].map(value => `<button data-split="${value}" class="${set.feature.split === value ? 'selected' : ''}"><b>${value.replace('-', '% / ')}%</b><span>${value === '80-20' ? '推荐' : '预设比例'}</span></button>`).join('')}</div>${button('完成特征工程', 'go-experiments', 'primary')}`;
}
function experimentsPage() {
  const set = dataset(); const list = set.experiments.map(id => state.experiments[id]).filter(Boolean);
  return shell(`${steps('experiments')}${pageHead('模型实验', '一个模型对应一个实验，同一模型可以创建多个实验。', button('＋ 新建模型实验', 'new-experiment', 'primary'))}<div class="experiment-grid">${list.map(item => `<article class="experiment-card" data-open-experiment="${item.id}"><div class="card-top"><span class="model-icon">${item.type.includes('lgbm') ? '⚡' : '◈'}</span><span class="status ${item.status === 'completed' ? 'good' : item.status === 'stale' ? 'blocked' : 'muted'}">${statusLabel(item.status)}</span></div><h3>${esc(item.name)}</h3><p>${modelName(item.type)} · ${item.standardize ? '已标准化' : '未标准化'} · ${tuningLabel(item.tuning)}</p>${item.results?.length ? metricPreview(item) : '<div class="empty-metric">尚未训练</div>'}<button class="text-link">打开实验 →</button></article>`).join('')}</div>`);
}
function tuningLabel(value) { return ({ auto: '快速自动调参', grid: '网格调参', bayesian: '贝叶斯调参', none: '不调参' }[value] || value); }
function metricPreview(item) { const result = item.results.find(row => row.id === item.selected) || item.results[0]; const task = state.projects.find(entry => entry.id === item.projectId)?.task; return task === 'regression' ? `<div class="mini-metrics"><span><b>${result.rmse}</b>RMSE</span><span><b>${result.r2}</b>R²</span></div>` : `<div class="mini-metrics"><span><b>${result.auc}</b>AUC</span><span><b>${result.ks}</b>KS</span></div>`; }
function modelSelectPage() { return shell(`${steps('experiments')}${pageHead('选择模型', `当前为${taskLabel(project().task)}项目，只展示适用模型。`, button('返回实验列表', 'go-experiments'))}<div class="model-grid">${modelCatalog[project().task].map(model => `<article class="model-card"><span>${model[0].includes('lgbm') ? '⚡' : '◈'}</span><h3>${model[1]}</h3><p>${model[2]}</p>${button('创建此模型实验', `add-model:${model[0]}`, 'primary')}</article>`).join('')}</div>`); }
function tuningOptions(item) { const bayes = ['lgbm', 'lgbmreg', 'forest', 'regforest'].includes(item.type); const grid = !['linear'].includes(item.type); return `<div class="tuning-options"><label class="${item.tuning === 'none' ? 'selected' : ''}"><input type="radio" name="tuning" value="none" ${item.tuning === 'none' ? 'checked' : ''}><b>不调参</b><span>使用当前参数直接训练</span></label>${grid ? `<label class="${item.tuning === 'auto' ? 'selected' : ''}"><input type="radio" name="tuning" value="auto" ${item.tuning === 'auto' ? 'checked' : ''}><b>快速自动调参 <em>推荐</em></b><span>无需设置算法和尝试次数</span></label><label class="${item.tuning === 'grid' ? 'selected' : ''}"><input type="radio" name="tuning" value="grid" ${item.tuning === 'grid' ? 'checked' : ''}><b>网格调参</b><span>使用预设值，可展开高级设置修改</span></label>` : ''}${bayes ? `<label class="${item.tuning === 'bayesian' ? 'selected' : ''}"><input type="radio" name="tuning" value="bayesian" ${item.tuning === 'bayesian' ? 'checked' : ''}><b>贝叶斯调参</b><span>系统优先搜索更有希望的参数区域</span></label>` : ''}</div>`; }
function experimentPage() {
  const item = experiment(); const defaultStandard = ['logistic', 'knn', 'linear'].includes(item.type);
  return shell(`${steps('experiments')}${pageHead(esc(item.name), `${modelName(item.type)} · ${esc(dataset().name)}`, `${button('返回实验列表', 'go-experiments')}${button('开始模拟训练', 'train', 'primary')}`)}<div class="config-grid"><section class="panel"><div class="panel-head"><div><h2>模型设置</h2><p>仅展示适合初学者的常用参数。</p></div></div><label class="field"><span>实验名称</span><input data-experiment-name value="${esc(item.name)}"></label><div class="field"><span>标准化</span><div class="toggle-line"><label class="switch"><input type="checkbox" data-standardize ${item.standardize ? 'checked' : ''}><span></span></label><b>${item.standardize ? '已开启' : '已关闭'}</b><small>该模型${defaultStandard ? '推荐开启' : '通常不需要'}标准化</small></div></div><div class="param-grid"><label>主要参数<input type="number" value="${item.type.includes('lgbm') ? 200 : 100}"></label><label>最大深度<input type="number" value="8"></label></div></section><section class="panel"><div class="panel-head"><div><h2>调参方式</h2><p>不适用的选项不会显示。</p></div><span class="mock">模拟调参</span></div>${tuningOptions(item)}${item.tuning === 'grid' ? `<details class="advanced"><summary>高级设置：修改候选值</summary><label>树数量<input value="100, 200, 300"></label><label>最大深度<input value="5, 8, 12"></label><button class="btn">恢复预设值</button></details>` : ''}</section></div>${state.training ? trainingPanel() : ''}`);
}
function trainingPanel() { return `<div class="training-panel"><div><b>${state.training.label}</b><span>${state.training.progress}%</span></div><div class="progress"><i style="width:${state.training.progress}%"></i></div><p>当前为模拟训练，结果用于展示前端流程。</p></div>`; }
function tuningPage() {
  const item = experiment(); if (!item?.results?.length) return shell(`${steps('tuning')}${pageHead('调参结果', '完成模型训练后查看参数结果。')}<div class="empty-state"><h2>还没有结果</h2>${button('返回模型实验', 'go-experiment', 'primary')}</div>`);
  const rows = state.showAllResults ? item.results : item.results.slice(0, 3); const regression = project().task === 'regression';
  return shell(`${steps('tuning')}${pageHead('调参结果', `${esc(project().name)} / ${esc(dataset().name)} / ${esc(item.name)} / ${modelName(item.type)}`, `${button(state.showAllResults ? '仅看 Top 3' : '查看全部结果', 'toggle-results')}${button('查看模型报告', 'go-report', 'primary')}`)}<div class="metric-direction"><span>${regression ? 'RMSE ↓ 越小越好' : 'AUC ↑ 越大越好'}</span><span>${regression ? 'R² ↑ 越大越好' : 'KS / F1 ↑ 越大越好'}</span><span>训练/验证差值 ↓ 越小越好</span></div><div class="top-result-grid">${rows.map((result, index) => `<article class="result-card ${index === 0 ? 'recommended' : ''}"><div class="rank">${index + 1}</div>${index === 0 ? '<em>当前最佳</em>' : ''}<h3>参数方案 #${result.id}</h3><p>${result.params}</p>${regression ? `<div class="result-metrics"><span><b>${result.rmse}</b>RMSE ↓</span><span><b>${result.mae}</b>MAE ↓</span><span><b>${result.r2}</b>R² ↑</span><span><b>${result.gap}</b>差值 ↓</span></div>` : `<div class="result-metrics"><span><b>${result.auc}</b>AUC ↑</span><span><b>${result.ks}</b>KS ↑</span><span><b>${result.f1}</b>F1 ↑</span><span><b>${result.gap}</b>差值 ↓</span></div>`}<div class="card-actions">${button('设为当前方案', `select-result:${result.id}`)}${button('查看详情', 'result-detail', 'primary')}</div></article>`).join('')}</div>`);
}
const metricHelp = {
  AUC: ['区分正负类的能力', '越大越好；0.8 以上通常表示区分能力较好'], KS: ['正负样本累计分布的最大差距', '越大越好；需结合样本和业务判断'], F1: ['精确率与召回率的综合平衡', '越大越好'], RMSE: ['对较大误差更敏感的平均误差', '越小越好；与基线或其他实验比较'], MAE: ['预测误差绝对值的平均', '越小越好；与目标值单位一致'], 'R²': ['模型解释目标变化的比例', '越大越好']
};
function metricCard(name, value) { return `<div class="metric-card"><span>${name}<i class="help" title="${metricHelp[name][0]}；${metricHelp[name][1]}">ⓘ</i></span><b>${value}</b><small>${metricHelp[name][1]}</small></div>`; }
function importanceMethod(type) { if (type.includes('lgbm')) return ['树模型原生重要性：分裂增益 Gain', '累计分裂增益']; if (type.includes('forest')) return ['树模型原生重要性：平均不纯度下降', '各树重要性的平均']; if (type.includes('tree')) return ['树模型原生重要性：不纯度下降', '节点分裂贡献']; if (['linear', 'logistic'].includes(type)) return ['标准化系数', '保留正负影响方向']; return ['排列重要性 Permutation Importance', '打乱特征后的效果下降']; }
function reportPage() {
  const item = experiment(); const regression = project().task === 'regression'; const best = item.results.find(row => row.id === item.selected) || item.results[0]; const method = importanceMethod(item.type); const features = dataset().columns.filter(column => column.included && !column.target).slice(0, 10);
  return shell(`${steps('report')}${pageHead('模型报告', `${esc(project().name)} / ${esc(dataset().name)} / ${esc(item.name)}`, `${button('返回调参结果', 'go-tuning')}${button('API 接入说明', 'go-api', 'primary')}`)}<div class="report-hero"><div><span class="status good">✓ 模拟训练成功</span><h2>${regression ? '模型已完成连续数值预测' : '模型已具备较好的正负类区分能力'}</h2><p>${regression ? '请结合 RMSE、MAE 和 R² 与其他实验进行比较。' : '建议同时关注 AUC、KS、F1 和业务需要的召回率。'}</p></div><div class="report-score"><b>${regression ? best.rmse : best.auc}</b><span>${regression ? 'RMSE ↓' : 'AUC ↑'}</span></div></div><div class="metrics-grid">${regression ? metricCard('RMSE', best.rmse) + metricCard('MAE', best.mae) + metricCard('R²', best.r2) : metricCard('AUC', best.auc) + metricCard('KS', best.ks) + metricCard('F1', best.f1)}</div>${regression ? regressionCharts() : classificationCharts()}<section class="section-block"><div class="section-title"><h2>变量重要性 Top ${features.length}</h2><span>不同计算方式的分数不可跨模型直接比较</span></div><div class="method-note"><b>${method[0]}</b><span>${method[1]}</span></div><div class="importance-list">${features.map((feature, index) => `<div><i>${index + 1}</i><b>${esc(feature.name)}</b><span><em style="width:${85 - index * 18}%"></em></span><strong>${(.46 - index * .11).toFixed(3)}</strong></div>`).join('')}</div></section><details class="metric-guide"><summary>指标说明与参考</summary>${Object.entries(metricHelp).filter(([name]) => regression ? ['RMSE', 'MAE', 'R²'].includes(name) : ['AUC', 'KS', 'F1'].includes(name)).map(([name, text]) => `<div><b>${name}</b><span>${text[0]}</span><em>${text[1]}</em></div>`).join('')}</details>`);
}
function classificationCharts() { return `<div class="chart-grid"><div class="chart-card"><h3>ROC 曲线</h3><div class="fake-chart roc"><i></i></div><p>曲线越靠近左上角，区分能力越好。</p></div><div class="chart-card"><h3>Gain Table</h3><table><thead><tr><th>累计人群</th><th>累计正类捕获</th><th>Lift</th></tr></thead><tbody><tr><td>10%</td><td>31%</td><td>3.10</td></tr><tr><td>20%</td><td>58%</td><td>2.90</td></tr><tr><td>30%</td><td>76%</td><td>2.53</td></tr></tbody></table></div></div>`; }
function regressionCharts() { return `<div class="chart-grid"><div class="chart-card"><h3>真实值与预测值</h3><div class="fake-chart scatter"><i></i><i></i><i></i><i></i></div><p>点越靠近对角线，预测越准确。</p></div><div class="chart-card"><h3>残差分布</h3><div class="fake-chart bars"><i></i><i></i><i></i><i></i><i></i></div><p>误差越集中在 0 附近越好。</p></div></div>`; }
function modelsPage() { const items = Object.values(state.experiments); return shell(`${pageHead('模型库', '按项目、数据集和模型实验管理当前最佳结果。')}<div class="filter-row"><select><option>全部项目</option>${state.projects.map(item => `<option>${esc(item.name)}</option>`).join('')}</select><select><option>全部任务</option><option>二分类</option><option>回归</option></select><select><option>全部状态</option><option>已完成</option><option>需要重新训练</option></select></div><div class="library-list">${state.projects.map(item => { const experiments = items.filter(exp => exp.projectId === item.id); return `<section><div class="section-title"><h2>${esc(item.name)}</h2><span>${taskLabel(item.task)} · ${experiments.length} 个模型</span></div><div class="experiment-grid">${experiments.map(exp => `<article class="experiment-card"><div class="card-top"><span class="model-icon">${exp.type.includes('lgbm') ? '⚡' : '◈'}</span><span class="status ${exp.status === 'completed' ? 'good' : 'blocked'}">${statusLabel(exp.status)}</span></div><h3>${esc(exp.name)}</h3><p>${modelName(exp.type)} · ${esc(state.datasets[exp.datasetId].name)}</p>${metricPreview(exp)}<div class="card-actions">${button('查看报告', `open-report:${exp.id}`)}${exp.status === 'completed' ? button('API 接入', `open-api:${exp.id}`, 'primary') : ''}</div></article>`).join('')}</div></section>`; }).join('')}</div>`); }
function apiPage() { const item = experiment(); return shell(`${pageHead('API 接入说明', `${esc(item.name)} · 演示接口，尚未部署真实模型服务`, button('返回模型报告', 'go-report'))}<div class="api-warning"><b>演示接口</b><span>当前请求只返回稳定模拟预测结果，不包含真实模型服务。</span></div><div class="api-grid"><section class="panel"><h2>接口信息</h2><div class="endpoint"><span>POST</span><code>https://demo.ml-studio.local/v1/predict/${item.id}</code>${button('复制', 'copy-endpoint')}</div><h3>请求 JSON</h3><pre>{
  "合同月数": 18,
  "月费用": 79.5,
  "套餐类型": "高级套餐"
}</pre><div class="code-tabs"><button>cURL</button><button>Python</button><button>JavaScript</button></div><pre>curl -X POST https://demo.ml-studio.local/v1/predict \\
  -H "Content-Type: application/json" \\
  -d '{"合同月数":18,"月费用":79.5}'</pre></section><section class="panel api-test"><h2>测试请求</h2><p>填写一组特征值，查看模拟响应。</p><label>合同月数<input value="18"></label><label>月费用<input value="79.5"></label>${button('发送模拟请求', 'test-api', 'primary')}<div id="api-response" class="api-response"><span>响应会显示在这里</span></div></section></div>`); }
function modal(content) { document.body.insertAdjacentHTML('beforeend', `<div class="modal-backdrop"><div class="modal">${content}</div></div>`); bindModal(); }
function newProjectModal() { modal(`<h2>创建项目</h2><p>创建后再上传数据集和选择目标列。</p><label class="field"><span>项目名称</span><input id="new-project-name" placeholder="例如：客户流失分析"></label><div class="field"><span>任务类型</span><div class="task-choice"><label><input type="radio" name="task" value="classification" checked> 二分类</label><label><input type="radio" name="task" value="regression"> 回归</label></div></div><small>创建时间将由系统自动生成。</small><div class="modal-actions">${button('取消', 'close-modal')}${button('创建项目', 'confirm-project', 'primary')}</div>`); }
function bindModal() { document.querySelector('.modal-backdrop [data-action="close-modal"]')?.addEventListener('click', () => document.querySelector('.modal-backdrop')?.remove()); document.querySelector('.modal-backdrop [data-action="confirm-project"]')?.addEventListener('click', () => { const name = document.querySelector('#new-project-name').value.trim(); if (!name) return toast('请输入项目名称。'); const task = document.querySelector('input[name="task"]:checked').value; const item = { id: uid('p'), name, task, createdAt: now(), updatedAt: now(), datasets: [] }; state.projects.push(item); state.projectId = item.id; document.querySelector('.modal-backdrop').remove(); save(); go('project'); }); }
function toast(message) { const element = document.querySelector('#toast'); if (!element) return; element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 2400); }
function action(name) {
  if (name === 'new-project') return newProjectModal();
  if (name === 'upload-dataset') return fileInput.click();
  if (name === 'go-feature') return go('feature'); if (name === 'go-experiments') return go('experiments'); if (name === 'go-experiment') return go('experiment'); if (name === 'go-tuning') return go('tuning'); if (name === 'go-report') return go('report'); if (name === 'go-api') return go('api');
  if (name === 'new-experiment') return go('model-select');
  if (name === 'next-feature') { state.featureStep = Math.min(3, state.featureStep + 1); save(); return render(); }
  if (name === 'apply-feature') { dataset().columns.forEach(column => { if (column.trainable && !column.target) column.included = column.missing <= .9 && (column.iv ?? 1) >= .01; }); dataset().feature.revision += 1; markDatasetStale(); save(); render(); return toast('已采用自动推荐。'); }
  if (name.startsWith('add-model:')) { const type = name.split(':')[1]; const count = dataset().experiments.map(id => state.experiments[id]).filter(item => item.type === type).length + 1; const id = uid('e'); const standardize = ['logistic', 'knn', 'linear'].includes(type); state.experiments[id] = { id, projectId: project().id, datasetId: dataset().id, name: `${modelName(type)} ${String(count).padStart(2, '0')}`, type, standardize, tuning: type === 'linear' ? 'none' : 'auto', status: 'draft', updatedAt: now(), results: [], selected: null }; dataset().experiments.push(id); state.experimentId = id; save(); return go('experiment'); }
  if (name === 'train') return startTraining();
  if (name === 'toggle-results') { state.showAllResults = !state.showAllResults; save(); return render(); }
  if (name.startsWith('select-result:')) { experiment().selected = +name.split(':')[1]; save(); render(); return toast('已更新当前最佳方案。'); }
  if (name.startsWith('open-report:')) { state.experimentId = name.split(':')[1]; state.datasetId = state.experiments[state.experimentId].datasetId; state.projectId = state.experiments[state.experimentId].projectId; return go('report'); }
  if (name.startsWith('open-api:')) { state.experimentId = name.split(':')[1]; state.datasetId = state.experiments[state.experimentId].datasetId; state.projectId = state.experiments[state.experimentId].projectId; return go('api'); }
  if (name === 'project-models') return go('models');
  if (name === 'test-api') { const response = document.querySelector('#api-response'); response.innerHTML = '<b>200 OK</b><pre>{ "prediction": "是", "probability": 0.78, "mock": true }</pre>'; return; }
  if (name === 'copy-endpoint') return toast('模拟接口地址已复制。');
}
function startTraining() { const item = experiment(); item.status = 'training'; state.training = { progress: 8, label: '正在校验配置' }; render(); const stages = [[28, '正在准备数据'], [52, item.tuning === 'auto' ? '正在快速自动调参' : '正在训练模型'], [78, '正在计算指标'], [100, '正在生成结果']]; let index = 0; const timer = setInterval(() => { state.training = { progress: stages[index][0], label: stages[index][1] }; render(); index += 1; if (index === stages.length) { clearInterval(timer); setTimeout(() => { item.results = makeResults(project().task, item.tuning === 'none' ? 1 : 8); item.selected = 1; item.status = 'completed'; item.updatedAt = now(); state.training = null; save(); go(item.tuning === 'none' ? 'report' : 'tuning'); }, 350); } }, 650); }
function parseCsv(text, name) { const rows = text.replace(/^\uFEFF/, '').trim().split(/\r?\n/).map(line => line.split(',')); if (rows.length < 2) return toast('CSV 至少需要表头和一行数据。'); const headers = rows[0].map(value => value.trim()); if (new Set(headers).size !== headers.length) return toast('CSV 表头不能重复。'); const data = rows.slice(1).filter(row => row.some(value => value.trim())); const columns = headers.map((header, index) => { const values = data.map(row => (row[index] || '').trim()); const nonempty = values.filter(Boolean); const numbers = nonempty.filter(value => !Number.isNaN(Number(value))).length; const type = numbers / Math.max(1, nonempty.length) > .9 ? 'number' : new Set(nonempty).size < Math.max(12, nonempty.length * .1) ? 'category' : 'text'; const unique = new Set(nonempty).size; const trainable = type !== 'text' || unique / Math.max(1, nonempty.length) < .5; return { name: header, type, missing: 1 - nonempty.length / Math.max(1, data.length), unique, trainable, reason: trainable ? '' : '自由文本或疑似 ID', iv: +(0.04 + index * .03).toFixed(2), psi: +(0.03 + index * .02).toFixed(2), included: trainable }; }); const id = uid('d'); const target = headers[headers.length - 1]; columns[columns.length - 1].target = true; columns[columns.length - 1].included = false; state.datasets[id] = { id, projectId: project().id, name: name.replace(/\.csv$/i, ''), uploadedAt: now(), rows: data.length, target, positive: project().task === 'classification' ? data[0][headers.length - 1] : '', columns, preview: data.slice(0, 150), feature: { missing: 'median', split: '80-20', revision: 1 }, experiments: [] }; project().datasets.push(id); state.datasetId = id; save(); go('dataset'); }
function bind() {
  app.querySelectorAll('[data-page]').forEach(element => element.onclick = () => go(element.dataset.page));
  app.querySelectorAll('[data-action]').forEach(element => element.onclick = event => { event.stopPropagation(); action(element.dataset.action); });
  app.querySelectorAll('[data-project]').forEach(element => element.onclick = () => { state.projectId = element.dataset.project; state.datasetId = project().datasets[0]; state.experimentId = dataset()?.experiments?.[0]; save(); go('project'); });
  app.querySelectorAll('[data-pop-tab]').forEach(element => element.onclick = event => { event.stopPropagation(); const popover = element.closest('.project-popover'); popover.querySelectorAll('[data-pop-tab]').forEach(tab => tab.classList.toggle('active', tab === element)); popover.querySelectorAll('[data-pop-panel]').forEach(panel => panel.classList.toggle('active', panel.dataset.popPanel === element.dataset.popTab)); });
  app.querySelectorAll('[data-open-project]').forEach(element => element.onclick = () => { state.projectId = element.dataset.openProject; state.datasetId = project().datasets[0]; state.experimentId = dataset()?.experiments?.[0]; save(); go('project'); });
  app.querySelectorAll('[data-open-dataset]').forEach(element => element.onclick = () => { state.datasetId = element.dataset.openDataset; state.experimentId = dataset().experiments[0]; save(); go('dataset'); });
  app.querySelectorAll('[data-open-experiment]').forEach(element => element.onclick = () => { state.experimentId = element.dataset.openExperiment; save(); go('experiment'); });
  app.querySelectorAll('[data-feature-step]').forEach(element => element.onclick = () => { state.featureStep = +element.dataset.featureStep; save(); render(); });
  app.querySelectorAll('[data-split]').forEach(element => element.onclick = () => { dataset().feature.split = element.dataset.split; dataset().feature.revision += 1; dataset().experiments.forEach(id => { if (state.experiments[id]?.status === 'completed') state.experiments[id].status = 'stale'; }); save(); render(); });
  app.querySelectorAll('[data-feature-toggle]').forEach(element => element.onchange = () => { const columns = dataset().columns.filter(column => !column.target); columns[+element.dataset.featureToggle].included = element.checked; dataset().feature.revision += 1; markDatasetStale(); save(); render(); });
  app.querySelectorAll('[data-column-type]').forEach(element => element.onchange = () => { const column = dataset().columns[+element.dataset.columnType]; column.type = element.value; column.trainable = column.target || !['date', 'text'].includes(element.value); column.reason = column.trainable ? '' : element.value === 'date' ? '原始日期字段' : '自由文本或疑似 ID'; markDatasetStale(); save(); render(); });
  app.querySelectorAll('input[name="tuning"]').forEach(element => element.onchange = () => { experiment().tuning = element.value; save(); render(); });
  document.querySelector('[data-standardize]')?.addEventListener('change', event => { experiment().standardize = event.target.checked; save(); render(); });
  document.querySelector('[data-experiment-name]')?.addEventListener('change', event => { experiment().name = event.target.value.trim() || experiment().name; save(); render(); });
}
function render() { const pages = { home: homePage, projects: projectsPage, project: projectPage, dataset: datasetPage, feature: featurePage, experiments: experimentsPage, 'model-select': modelSelectPage, experiment: experimentPage, tuning: tuningPage, report: reportPage, models: modelsPage, api: apiPage }; app.innerHTML = (pages[state.page] || homePage)(); bind(); }
fileInput.addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => parseCsv(String(reader.result), file.name); reader.readAsText(file, 'utf-8'); event.target.value = ''; });
render();
